---
title: "Figures"
author: "Victor Van der Meersch"
date: "2024-06-18"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

rm(list=ls());gc()
wd <- "~/projects/future_forests"

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.path= paste0(wd, "/newfigures/files/"))
chunkhooks::hook_figure_unit("mm")

library(terra)
library(sf)
library(dplyr)
library(rnaturalearth)
library(lubridate)
library(cowplot)
library(zoo)
library(ggplot2)
library(future.apply)
library(doFuture)
library(tidyterra)
library(ggpattern)
library(RColorBrewer)
library(khroma)
library(grid)
library(car)
library(ggeffects)
library(patchwork)

```

```{r load_ecoregions, eval = TRUE}

source(file.path(wd, "newfigures", "scripts", "ecoregions.R"))

```

<!---  ## Prepare data --->

```{r load_csdm_maps, eval = FALSE}

nsim <- 20
breakseq <- seq(0, nsim, 1)
models <- c("lasso_glm", "random_forest", "gam", "brt")
species_list <- c("abies_alba","fagus_sylvatica","quercus_petraea","quercus_robur","quercus_pubescens","quercus_ilex","betula_pendula","fraxinus_excelsior","pinus_sylvestris")

for(species in species_list){
  source(file.path(wd, "newfigures", "scripts", "fig4", "load_csdm_maps.R"))
}

```

```{r load_pbm_maps, eval = FALSE}

nsim <- 50
breakseq <- seq(0, nsim, 10)
calibrations <- (paste0("subset",rep(1:2, each = 5),"_rep", 1:5))
type <- "fitted"
ncores <- 10
species_list <- c("betula_pendula","fraxinus_excelsior","pinus_sylvestris")

for(species in species_list){
  source(file.path(wd, "newfigures", "scripts", "fig4", "load_pbm_maps.R"))
}

nsim <- 5
breakseq <- seq(0, nsim, 1)
calibrations <- 'expert'
type <- "expert"
ncores <- 1
species_list <- c("betula_pendula","fraxinus_excelsior","pinus_sylvestris")

for(species in species_list){
  source(file.path(wd, "newfigures", "scripts", "fig4", "load_pbm_maps.R"))
}


```

<!---  ## ANOVA-based partitioning within each species --->

```{r anova_within_species_byecoregion, fig.height = 90, fig.width = 130, fig.cap = "ANOVA-based partitioning within species", dev = "cairo_pdf", eval = TRUE}

# switch
reload_data <- FALSE

scenarios <- c("ssp245", "ssp585")
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
ecoregions <- c("Atlantic", "Boreal", "Mediterranean", "Continental", "Alpine")

# models
csdms <- c("lasso_glm", "gam", "brt", "random_forest")
pbms <- list(abies_alba = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             fagus_sylvatica = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             quercus_petraea = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             quercus_robur = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             quercus_pubescens = c("expert", paste0("subset",rep(1, each = 5),"_rep", 1:5)),
             quercus_ilex = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             betula_pendula = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             fraxinus_excelsior = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             pinus_sylvestris = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5))
             )
species_list <- names(pbms)

# loop across the five ecoregions
saved_data_species <- data.frame()
data_barplot <- data.frame()
for(ecoregion in ecoregions){
  
  anova_sp <- foreach(species = species_list, .combine=rbind) %do% {
    if(reload_data){
      
      # load simulations of PBMs
      ncores <- 3
      source(file.path(wd, "newfigures", "scripts", "fig1", "load_yearly_fitness_pbm.R"))
      saveRDS(simulations_pbm, file.path(wd,"newfigures","data", "sims", paste0("pbm_", species, "_", ecoregion, ".rds")))

      # load simulations of CSDMs
      source(file.path(wd, "newfigures", "scripts", "fig1", "load_yearly_fitness_csdm.R"))
      saveRDS(simulations_csdm, file.path(wd,"newfigures", "data", "sims", paste0("csdm_", species, "_", ecoregion, ".rds")))
      
    }else{
      simulations_pbm <- readRDS(file.path(wd, "newfigures", "data", "sims", paste0("pbm_", species, "_", ecoregion, ".rds")))
      simulations_csdm <- readRDS(file.path(wd, "newfigures","data", "sims", paste0("csdm_", species, "_", ecoregion, ".rds"))) 
    }
    
    # 21-year average fitness (already done for CSDM)
    simulations_pbm <- simulations_pbm %>%
      group_by(cal, gcm, ssp) %>% 
      mutate(y = rollapply(y,21,mean,align='center',fill=NA)) %>%
      ungroup %>% na.omit()
    
    # ensemble by method
    sim <- rbind(simulations_pbm, simulations_csdm)
    sim$method <- ifelse(sim$cal == "expert", "expert", 
                         ifelse(sim$cal %in% csdms, "correlative", "fitted"))
    simulations <- sim %>%
      group_by(ssp, gcm, method, year) %>%
      summarise(y = mean(y), species = species) %>% ungroup()
    
    saved_data_species <-  rbind(saved_data_species, 
                             simulations %>%
                               dplyr::filter(year %in% c(1990:2100)) %>%
                               group_by(ssp, gcm, method, species, year) %>%
                               summarise(y = mean(y)) %>%
                               ungroup() %>%
                               group_by(year,species) %>%
                               reframe(meany = mean(y), int = sd(y)) %>%
                               mutate(ecoregion = ecoregion))
    
    source(file.path(wd, "figures_cleaned", "scripts", "fig3", "anova_within_species.R"))
    
    anova_ss
    
  }
  
  anova_sp$ecoregion <- ecoregion
  
  data_barplot <- rbind(data_barplot, anova_sp)
  
}

species_order <- c("pinus_sylvestris", "abies_alba", "betula_pendula", "fraxinus_excelsior", "fagus_sylvatica", "quercus_petraea", "quercus_robur", "quercus_pubescens", "quercus_ilex") 

data_barplot <- data_barplot %>%
    left_join(saved_data_species %>% filter(year == 2090), by = c("year", "ecoregion", "species")) %>%
    mutate(ecoregion = factor(ecoregion, levels = rev(c("Boreal", "Alpine", "Continental", "Atlantic", "Mediterranean"))))
  

source(file.path(wd, "newfigures", "scripts", "fig3", "barplot_uncertainty_withinspecies.R"))
source(file.path(wd, "newfigures", "scripts", "fig3", "inset_piecharts.R"))
source(file.path(wd, "newfigures", "scripts", "fig3", "inset_legend.R"))
source(file.path(wd, "newfigures", "scripts", "fig3", "inset_summary.R"))

design <-
  "12
   13
   14"

assemble_fig <- barplot_prop_uncertainty_withinspecies + inset_element(piecharts, l = 0-0.03, r = 1+0.03,  t = 0.3, b = -0.1, clip = FALSE) +
  insetlegend + plot_summary+ ecoregions_map + theme(legend.position = 'none') +
  plot_layout(design = design, heights = c(0.48, 0.26, 0.62), widths = c(.7, .3))

assemble_fig #+
 # draw_plot(insetlegend, x = 0.78, y = .4, width = 1.2, height = .4)

cat("ANOVA-based partitioning within species")
knitr::kable(data_barplot %>%
  group_by(ecoregion, species) %>%
  reframe(sdm/tot*100, gcm/tot*100, climate = (gcm+ssp+gcm.ssp)/tot*100))

knitr::kable(data_barplot %>%
  group_by(ecoregion) %>%
  summarise(sdm = mean(sdm/tot*100), climate = mean((gcm+ssp+gcm.ssp)/tot*100), gcm = mean(gcm/tot*100), ssp = mean(ssp/tot*100)))

knitr::kable(data_barplot %>%
  group_by(species) %>%
  summarise(sdm = mean(sdm/tot*100), climate = mean((gcm+ssp+gcm.ssp)/tot*100), gcm = mean(gcm/tot*100), ssp = mean(ssp/tot*100)))

knitr::kable(data_barplot %>%
  summarise(sdm = mean(sdm/tot*100), climate = mean((gcm+ssp+gcm.ssp)/tot*100), gcm = mean(gcm/tot*100), ssp = mean(ssp/tot*100)))


```

```{r allspecies_cascade, fig.height = 70, fig.width = 120, fig.cap = "All species, ssp2", dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 
target_ext <- ext(-10.5, 31.7, 34.6, 71.2)
ytext <- 0.4

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenarios <- c("ssp245", "ssp585")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

csdms <- c("lasso_glm", "gam", "brt", "random_forest")
pbms <- list(fagus_sylvatica = c("expert",
                                 paste0("subset",rep(1:10, each = 10),"_rep", 1:10),
                                 paste0("partial/subset",rep(1:2, each = 5),"_rep", 1:5)))
yr <- '2080-2100'
source('~/projects/future_forests/newfigures/scripts/appendix/cascade_bonus_new.R')

cascade_all_models

```

```{r allspecies_distribution_maps, fig.height = 210, fig.width = 170, fig.cap = "All species, ssp2", dev = "cairo_pdf", eval = FALSE}

scenario <- "ssp245"

for(species in species_list){
  type <- "csdm"
  sim_dist_2090 <- readRDS(file = file.path(wd,"newfigures","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
  source(file.path(wd, 'newfigures', 'scripts', 'distribution_map.R'))
  csdm_dist2090 <- dist_map_lessmore
  
  type <- "expert"
  sim_dist_2090 <- readRDS(file = file.path(wd,"newfigures","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
  source(file.path(wd, 'newfigures', 'scripts', 'distribution_map.R'))
  epbm_dist2090 <- dist_map_lessmore
  
  type <- "fitted"
  sim_dist_2090 <- readRDS(file = file.path(wd,"newfigures","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
  source(file.path(wd, 'newfigures', 'scripts', 'distribution_map.R'))
  fpbm_dist2090 <- dist_map_lessmore
  
  
  maps <- plot_grid(
    csdm_dist2090 + theme(legend.position = 'none'), NULL,
    fpbm_dist2090 + theme(legend.position = 'none'), NULL,
    epbm_dist2090 + theme(legend.position = 'none'),
    rel_widths = c(1,0.05,1,0.05,1), vjust = 2, hjust = -1,
    nrow = 1)
  
  maps <- plot_grid(
    csdm_dist2090 + theme(legend.position = 'none'), 
    fpbm_dist2090 + theme(legend.position = 'none'), 
    epbm_dist2090 + theme(legend.position = 'none'),
    vjust = 2, hjust = -1,
    nrow = 1)
  
  assign(paste("maps", species, sep = "_"), maps)
}

design <-
  "ABC
   DEF
   GGG
   HHH
   IJK
   LMN"

assemble_fig <- 
  maps_pinus_sylvestris + plot_spacer() + maps_abies_alba + 
  maps_betula_pendula + plot_spacer() + maps_fraxinus_excelsior + 
  maps_fagus_sylvatica +
  plot_spacer() + 
  maps_quercus_robur + plot_spacer() + maps_quercus_petraea + 
  maps_quercus_pubescens + plot_spacer() + maps_quercus_ilex + 
  plot_layout(design = design,  widths = c(1, 0.1, 1), heights = c(0.8, 0.8, 1.7,0.5))

```

```{r fagussylvatica_distribution_maps, fig.height = 90, fig.width = 180, fig.cap = "Fagus sylvatica, ssp2", dev = "cairo_pdf", eval = FALSE}

scenario <- "ssp245"
species <- "fagus_sylvatica"

type <- "csdm"
sim_dist_2090 <- readRDS(file = file.path(wd,"newfigures","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
source(file.path(wd, 'newfigures', 'scripts', 'distribution_map.R'))
csdm_dist2090 <- dist_map_lessmore
  
type <- "expert"
sim_dist_2090 <- readRDS(file = file.path(wd,"newfigures","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
source(file.path(wd, 'newfigures', 'scripts', 'distribution_map.R'))
  epbm_dist2090 <- dist_map_lessmore
  
type <- "fitted"
sim_dist_2090 <- readRDS(file = file.path(wd,"newfigures","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
source(file.path(wd, 'newfigures', 'scripts', 'distribution_map.R'))
fpbm_dist2090 <- dist_map_lessmore
  
  
plot_grid(
  plot_grid(csdm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          fpbm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          epbm_dist2090 + theme(legend.position = 'none'),
          rel_widths = c(1,0.05,1,0.05,1), vjust = 2, hjust = -1,
          nrow = 1, labels = c("a ", NA,"b", NA, "c"), label_size = 10, label_colour = 'grey30'),
  cowplot::get_plot_component(csdm_dist2090 + theme(legend.position = 'right', legend.title = element_blank()), 'guide-box-right', return_all = TRUE),
  NULL, NULL, ncol = 2, rel_widths = c(1, 0.18), rel_heights = c(1, 0.63))


```

```{r load_simulations, fig.height = 70, fig.width = 80, fig.cap = "ANOVA-based partitioning across species", dev = "cairo_pdf", eval = FALSE}

# switches
reload_data <- FALSE

scenarios <- c("ssp245", "ssp585")
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
ecoregions <- c("Atlantic", "Boreal", "Mediterranean", "Continental", "Alpine")

csdms <- c("lasso_glm", "gam", "brt", "random_forest")
pbms <- list(abies_alba = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             fagus_sylvatica = c("expert", paste0("subset",rep(1:10, each = 10),"_rep", 1:10)),
             quercus_petraea = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             quercus_robur = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             quercus_pubescens = c("expert", paste0("subset",rep(1, each = 5),"_rep", 1:5)),
             quercus_ilex = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             betula_pendula = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             fraxinus_excelsior = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             pinus_sylvestris = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5))
             )

species_list <- names(pbms)

simulations <- foreach(species = species_list, .combine=rbind) %do% {
  
    if(reload_data){
      
      # load simulations of PBMs
      ncores <- 20
      source(file.path(wd, "newfigures", "scripts", "fig2", "load_yearly_fitness_pbm_bycell.R"))
      
      # load simulations of CSDMs
      source(file.path(wd, "newfigures", "scripts", "fig2", "load_yearly_fitness_csdm_bycell.R"))
      
      # ensemble by method
      sim <- rbind(simulations_pbm, simulations_csdm)
      rm(simulations_pbm, simulations_csdm)
      gc(verbose = FALSE)
    
      sim$method <- ifelse(sim$cal == "expert", "expert",
                         ifelse(sim$cal %in% csdms, "correlative", "fitted"))
    
      sim <- sim %>%
        group_by(ssp, gcm, method, id_cell, x, y) %>%
        summarise(mean = mean(mean), species = species) %>% ungroup()
      gc(verbose = FALSE)
      
      saveRDS(sim, file.path(wd,"newfigures","data", "sims", paste0("allsim_", species, "_", "bycell", ".rds")))
      
    }else{
      sim <- readRDS(file.path(wd,"newfigures","data", "sims", paste0("allsim_", species, "_", "bycell", ".rds")))
    }
    
    sim
}
gc(verbose = FALSE)

  
source(file.path(wd, "newfigures", "scripts", "fig2", "suitability_map.R"))

map_suitability_3zones


```

```{r suit3, fig.height = 80, fig.width = 165, fig.cap = "ANOVA-based partitioning across species", dev = "cairo_pdf", eval = FALSE}

map_suitability_3zones <- ggplot() +
  geom_spatraster(data = suit_r, maxcell = 1e+05) +
  geom_sf_pattern(data = sim_agreement, 
                  aes(pattern = value),
                  color = NA, fill = NA,
                  pattern_colour = NA,
                  pattern_fill = "grey50",
                  pattern_angle = 45,
                  pattern_density = 0.2,
                  pattern_spacing = 0.015,
                  pattern_key_scale_factor = 3) +
  scale_pattern_manual(values = c(Low = "stripe"), labels = c("Low model agreement"), name = NULL) +
  geom_spatvector(data = ctr2 %>%  simplifyGeom(tolerance=5000, preserveTopology=TRUE, makeValid=FALSE), 
                  color = "grey40", fill = NA, linewidth = 0.1) +
  theme_void() +
  
  # scale_y_continuous(expand = c(0, 0), limits = c(1287903, 5459220)) +
  # scale_x_continuous(expand = c(0, 0), limits = c(2440871, 6306970)) +
  
  theme(
    legend.title = element_blank(),
    legend.title.position = 'top',
    legend.text = element_text(size = 6.5, color = 'grey20'),
    legend.position = "bottom", legend.box="horizontal",
    legend.box.margin = margin(t = 0, b = 0, r = 0, l = 0),
    plot.margin = margin(t=5.5,b=5.5,l=60,r=60),
    strip.text = element_text(size = 8, margin = margin(t=0,b=5,l=0,r=0)),
    panel.border = element_rect(colour = NA, fill=NA, linewidth=0.4),
    panel.grid.major = element_line(color = "grey90")) +
  scale_fill_gradient2(
    low = "#a63716",
    mid = "#eef0f1",
    high = "#15607a",
    na.value = "transparent", 
    limits = c(-0.45, 0.45),
    breaks = seq(-0.4, 0.4, 0.2), 
    labels = c("-0.4", "-0.2", "0", "0.2", "0.4"),
    name = 'Change in suitability'
  ) +
  guides(
    fill = guide_colorbar(order = 2,
                          frame.colour = "grey30", ticks.colour = NA,
                          frame.linewidth = 0.2,
                          theme = theme(legend.key.height  = unit(5, "pt"),
                                        legend.key.width  = unit(120, "pt"),
                                        legend.text = element_text(size = 6.5, margin = margin(t = 3.5)))),
    pattern = guide_legend(override.aes = list(fill = "white", color = "grey30"), order = 1,
                           theme = theme(legend.key.height  = unit(6, "pt"),
                                         legend.text = element_text(size = 7)))) +
  geom_spatvector(data = ctratlmed, 
                  color = "white", fill = NA, linewidth = 0.8) +
  geom_spatvector(data = ctratlmed, 
                  color = "#a63716", fill = NA, linewidth = 0.25) +
  geom_spatvector(data = ctrcont, 
                  color = "white", fill = NA, linewidth = 0.8) +
  geom_spatvector(data = ctrcont, 
                  color = "#607a15", fill = NA, linewidth = 0.25) +
  geom_spatvector(data = ctrbor, 
                  color = "white", fill = NA, linewidth = 0.8) +
  geom_spatvector(data = ctrbor, 
                  color = "#15607a", fill = NA, linewidth = 0.25) +
  
  geom_spatvector(data = ctratlmed_pt, 
                  color = "#a63716", fill = NA, size = 1.375) +
  geom_spatvector(data = ctratlmed_line, 
                  color = "#a63716", fill = NA, linewidth = 0.3) +
  geom_spatvector(data = ctratlmed_pt, 
                color = "white", fill = 'white', size = 0.93) +
  geom_spatvector(data = ctratlmed_pt, 
                  color = "#a63716", fill = NA, size = 0.25) +
  
  annotate(geom = 'point', size = 1.375, color = '#a63716',
           y = 2e06, x = 3100000) +
  annotate(geom = 'segment', linewidth = 0.3, color = '#a63716',
           y = 2e06, yend = 2e06, x = 1940871, xend = 3100000) +
  annotate(geom = 'segment', linewidth = 0.3, color = '#a63716',
           y = 2e06-4.5e5, yend = 2e06+4.5e5, x = 1940871, xend = 1940871) +
  annotate("text", x = 1940871+3e4, y = 2e06+6e5, label = "Mediterranean and Atlantic forests", 
           hjust = 1, color = '#a63716', size = 2.5) +
  annotate("text", x = 1940871-1e5, y = 2e06, 
           label = 
             paste("Some fact...", "High agreement between models",
                   'Overall decrease in suitability', 'Introduce better-adapted populations (and species)', sep = '\n'), 
           hjust = 1, color = 'grey40', size = 2.2) +
  annotate(geom = 'point', size = 0.93, color = 'white',
           y = 2e+06, x = 3100000) +
  annotate(geom = 'point', size = 0.25, color = '#a63716',
           y = 2e+06, x = 3100000) +
  
  annotate(geom = 'point', size = 1.375, color = '#607a15',
           y = 3200000, x = 5300000) +
  annotate(geom = 'segment', linewidth = 0.3, color = '#607a15',
           y = 3200000, yend = 3200000, x = 5300000, xend = 6806970) +
  annotate(geom = 'segment', linewidth = 0.3, color = '#607a15',
           y = 3200000-4.5e5, yend = 3200000+4.5e5, x = 6806970, xend = 6806970) +
  annotate("text", x = 6806970-3e4, y = 3200000+6e5, label = "Continental & mid-mountain forests", 
           hjust = 0, color = '#607a15', size = 2.5) +
  annotate("text", x = 6806970+1e5, y = 3200000, 
           label = 
             paste("41.9% of total timber harvest (2000-2010)", "Low agreement between models",
                   'No clear trend in suitability',  'Increase diversity to mitigate risks', sep = '\n'), 
           hjust = 0, color = 'grey40', size = 2.2) +
  annotate(geom = 'point', size = 0.93, color = 'white',
           y = 3200000, x = 5300000) +
  annotate(geom = 'point', size = 0.25, color = '#607a15',
           y = 3200000, x = 5300000) +
  
  annotate(geom = 'point', size = 1.375, color = '#15607a',
           y = 4500000, x = 4550000) +
  annotate(geom = 'segment', linewidth = 0.3, color = '#15607a',
           y = 4500000, yend = 4500000, x = 1940871, xend = 4550000) +
  annotate(geom = 'segment', linewidth = 0.3, color = '#15607a',
           y = 4500000-4.5e5, yend = 4500000+4.5e5, x = 1940871, xend = 1940871) +
  annotate("text", x = 1940871+3e4, y = 4500000+6e5, label = "North European & Alps forests", 
           hjust = 1, color = '#15607a', size = 2.5) +
  annotate("text", x = 1940871-1e5, y = 4500000, 
           label = 
             paste("Dominated by coniferous forests", "High agreement between models", # 32.1% of total timber harvest (2000-2010)
                   'Overall increase in suitability', 'Consider new opportunities to improve resilience', sep = '\n'), 
           hjust = 1, color = 'grey40', size = 2.2) +
  annotate(geom = 'point', size = 0.93, color = 'white',
           y = 4500000, x = 4550000) +
  annotate(geom = 'point', size = 0.25, color = '#15607a',
           y = 4500000, x = 4550000) +
  
  coord_sf(clip = 'off', xlim = c(2440871, 6306970),
           ylim = c(1287903, 5459220), expand = FALSE) +
   annotate("text", x = 5680000, y = 1.05e06, label = "Average suitability change", 
           hjust = 0.5, color = 'grey20', size = 2.4) 


plot_spacer() + map_suitability_3zones + plot_spacer() +
  plot_layout(nrow = 1, width = c(.55,1,.55))

```

<!---  ## ANOVA-based partitioning within each species, only CSDM --->

```{r anova_within_species_byecoregion_onlycsdm, fig.height = 100, fig.width = 80, fig.cap = "ANOVA-based partitioning within species - ONLY CSDM", dev = "cairo_pdf", eval = FALSE}

# switch
reload_data <- FALSE

scenarios <- c("ssp245", "ssp585")
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
ecoregions <- c("Atlantic", "Boreal", "Mediterranean", "Continental", "Alpine")

csdms <- c("lasso_glm", "gam", "brt", "random_forest")

# empty dataframes to save intermediary outputs for some other figures
saved_data_species <- data.frame()

# loop across the five ecoregions
data_barplot <- data.frame()
for(ecoregion in ecoregions){
  
  anova_sp <- foreach(species = species_list, .combine=rbind) %do% {
    if(reload_data){

      # load simulations of CSDMs
      source(file.path(wd, "figures_cleaned", "scripts", "fig1", "load_yearly_fitness_csdm.R"))
      saveRDS(simulations_csdm, file.path(wd,"figures_cleaned", "data", "sims", paste0("csdm_", species, "_", ecoregion, ".rds")))
      
    }else{
      
      simulations_csdm <- readRDS(file.path(wd, "figures_cleaned","data", "sims", paste0("csdm_", species, "_", ecoregion, ".rds"))) 
    }
    
    simulations <- simulations_csdm %>%
      mutate(method = cal, species = species)
    
    # ensemble by method
    simulations <- simulations %>%
      group_by(ssp, gcm, method, year) %>%
      summarise(y = mean(y), species = species) %>% ungroup()
    
    saved_data_species <-  rbind(saved_data_species, 
                             simulations %>%
                               dplyr::filter(year %in% c(1990:2100)) %>%
                               group_by(ssp, gcm, method, species, year) %>%
                               summarise(y = mean(y)) %>%
                               ungroup() %>%
                               group_by(year,species) %>%
                               reframe(meany = mean(y), int = sd(y)) %>%
                               mutate(ecoregion = ecoregion))
    
    source(file.path(wd, "figures_cleaned", "scripts", "fig3", "anova_within_species.R"))
    
    anova_ss
    
  }
  
  anova_sp$ecoregion <- ecoregion
  
  data_barplot <- rbind(data_barplot, anova_sp)
  
}

data_barplot <- data_barplot %>%
    left_join(saved_data_species %>% filter(year == 2090), by = c("ecoregion", "species")) %>%
    mutate(ecoregion = factor(ecoregion, levels = rev(c("Boreal", "Alpine", "Continental", "Atlantic", "Mediterranean"))))

# source(file.path(wd, "figures_cleaned", "scripts", "fig2", "barplot_uncertainty_across_species.R"))
source(file.path(wd, "figures_cleaned", "scripts", "fig3", "barplot_uncertainty_withinspecies.R"))


barplot_prop_uncertainty_withinspecies +
  draw_plot(insetlegend, x = 0.78, y = .4, width = 1.2, height = .4) +
  scale_fill_manual(name = "",
                    breaks = c("ssp", "gcm.ssp", "gcm", "sdm.climate", "sdm", "residuals"),
                    labels = c("SSP", "SSP - GCM", "GCM", "Climate - CSDM", "CSDM", "Residuals"),
                    values=cols)

cat("ANOVA-based partitioning within species")
knitr::kable(data_barplot %>%
  group_by(ecoregion, species) %>%
  reframe(sdm/tot*100, gcm/tot*100, climate = (gcm+ssp+gcm.ssp)/tot*100))

knitr::kable(data_barplot %>%
  group_by(ecoregion) %>%
  summarise(sdm = mean(sdm/tot*100), climate = mean((gcm+ssp+gcm.ssp)/tot*100), gcm = mean(gcm/tot*100), ssp = mean(ssp/tot*100)))

knitr::kable(data_barplot %>%
  group_by(species) %>%
  summarise(sdm = mean(sdm/tot*100), climate = mean((gcm+ssp+gcm.ssp)/tot*100), gcm = mean(gcm/tot*100), ssp = mean(ssp/tot*100)))

knitr::kable(data_barplot %>%
  summarise(sdm = mean(sdm/tot*100), climate = mean((gcm+ssp+gcm.ssp)/tot*100), gcm = mean(gcm/tot*100), ssp = mean(ssp/tot*100)))


```