---
title: "Figures"
author: "Victor Van der Meersch"
date: "2024-06-18"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
wd <- "C:/Users/vandermeersch/Documents/CEFE/projects/future_forests"

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.path= paste0(wd, "/figures_cleaned/files/"))
chunkhooks::hook_figure_unit("mm")

library(terra)
library(sf)
library(dplyr)
library(rnaturalearth)
library(lubridate)
library(cowplot)
library(zoo)
library(ggplot2)
library(future.apply)
library(doFuture)
library(tidyterra)
library(ggpattern)
library(RColorBrewer)
library(khroma)
library(grid)
```

<!---  ## Fagus sylvatica divergent simulations --->

```{r fagus_fittedPEM_simulations, dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "fagus_sylvatica"

nsim <- 500
breakseq <- seq(0, nsim, 100)

calibrations <- (paste0("subset",rep(1:10, each = 10),"_rep", 1:10))
type <- "fitted"
ncores <- 10

# load simulations
if(reload_data){
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_pbm_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_distribution_", scenario, ".rds")))
  sim_dist_2090 <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
}

# fitness maps
panel_color <- "#995D81"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))

fpbm_fit2050 <- fitness_map_2050
fpbm_fit2090 <- fitness_map_2090
fpbm_dist2090 <- dist_map_lessmore
fpbm_agreement <- sim_agreement

fpbm_r2090 <- subset(sim_fitness,2)

```

```{r fagus_expertPEM_simulations, dev = "cairo_pdf", eval = TRUE}

#switch
reload_data <- FALSE 

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "fagus_sylvatica"

nsim <- 5
breakseq <- seq(0, nsim, 1)

calibrations <- 'expert'
type <- 'expert'
ncores <- 1

# load simulations
if(reload_data){
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_pbm_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_distribution_", scenario, ".rds")))
  sim_dist_2090 <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
}

# fitness maps
panel_color <- "#018530"
# panel_color <- "grey80"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))

epbm_fit2050 <- fitness_map_2050
epbm_fit2090 <- fitness_map_2090
epbm_dist2090 <- dist_map_lessmore
epbm_agreement <- sim_agreement

epbm_r2090 <- subset(sim_fitness,2)

```

```{r fagus_CSDM_simulations, dev = "cairo_pdf", eval = FALSE}

nsim <- 20
breakseq <- seq(0, nsim, 1)

models <- c("lasso_glm", "random_forest", "gam", "brt")

# load simulations
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_csdm_maps.R"))

crs(sim_fitness) <- "EPSG:4326"
crs(sim_distribution) <- "EPSG:4326"
crs(sim_agreement) <- "EPSG:4326"

# fitness maps
panel_color <- "#457b9d"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))

csdm_fit2050 <- fitness_map_2050
csdm_fit2090 <- fitness_map_2090
csdm_dist2090 <- dist_map_lessmore
csdm_agreement <- sim_agreement

csdm_r2090 <- subset(sim_fitness,2)

```

```{r fagus_partialPEM_simulations, dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "fagus_sylvatica"

nsim <- 50
breakseq <- seq(0, nsim, 20)

calibrations <- (paste0("partial/subset",rep(1:2, each = 5),"_rep", 1:5))
type <- "partial"
ncores <- 10

# load simulations
if(reload_data){
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_pbm_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_distribution_", scenario, ".rds")))
  sim_dist_2090 <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
}

# fitness maps
panel_color <- "#d2c024"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))

ppbm_fit2050 <- fitness_map_2050
ppbm_fit2090 <- fitness_map_2090
ppbm_dist2090 <- dist_map_lessmore
ppbm_agreement <- sim_agreement

```

```{r fagus_cascade, fig.height = 160, fig.width = 190, fig.cap = "Fagus sylvatica, ssp2", dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 
target_ext <- ext(-10.5, 31.7, 34.6, 71.2)
ytext <- 0.4

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenarios <- c("ssp245", "ssp585")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "fagus_sylvatica"

csdms <- c("lasso_glm", "gam", "brt", "random_forest")
pbms <- list(fagus_sylvatica = c("expert",
                                 paste0("subset",rep(1:10, each = 10),"_rep", 1:10),
                                 paste0("partial/subset",rep(1:2, each = 5),"_rep", 1:5)))

# load simulations
if(reload_data){
  # load simulations of PBMs
  ncores <- 5
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_yearly_fitness_pbm_all.R"))
  saveRDS(simulations_pbm, file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_Europe", ".rds")))

  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_yearly_fitness_csdm_all.R"))
  saveRDS(simulations_csdm, file.path(wd,"figures_cleaned","data", "sims", paste0("csdm_", species, "_Europe", ".rds")))
  
}else{
  simulations_pbm <- readRDS(file = file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_Europe", ".rds")))
  simulations_csdm <- readRDS(file = file.path(wd,"figures_cleaned","data", "sims", paste0("csdm_", species, "_Europe", ".rds")))
}

simulations <- rbind(simulations_pbm,simulations_csdm)

source(file.path(wd, "figures_cleaned", "scripts", "fig4", "uncertainty_cascade_wpartial.R"))

plot_grid(
  plot_grid(epbm_fit2050 + theme(legend.position = 'none'), 
            ppbm_fit2050 + theme(legend.position = 'none'), 
            fpbm_fit2050 + theme(legend.position = 'none'), 
            csdm_fit2050 + theme(legend.position = 'none'),
            ncol = 1),
  NULL,
  plot_grid(NULL, plot_grid(cascade1, NULL, cascade2, nrow = 1, rel_widths = c(1.1,-0.1,1)), 
            NULL,
            cowplot::get_plot_component(cascade2 + theme(legend.position = 'bottom'), 'guide-box-bottom', return_all = TRUE), 
            cowplot::get_plot_component(fpbm_fit2090, 'guide-box-bottom', return_all = TRUE), 
            ncol = 1, rel_heights = c(1.8,5, 0.8, 0.9, 0.9)),
  NULL,
  plot_grid(epbm_fit2090 + theme(legend.position = 'none'),
            ppbm_fit2050 + theme(legend.position = 'none'),
            fpbm_fit2090 + theme(legend.position = 'none'), 
            csdm_fit2090 + theme(legend.position = 'none'),
            ncol = 1),
  ncol = 5, rel_widths = c(1, -0.1, 1.1, -0.1, 1)) +
  draw_text("2040-2060", x = 2/5, y = 4/5+0.05, size = 10) +
  draw_text("2080-2100", x = 3/5, y = 4/5+0.05, size = 10) +
  draw_text("Projected change in suitability\nrelative to 1970-2000", x = 1/2, y = 1/5+0.06, size = 8.5)
  

```

```{r cascade_bonus, fig.height = 60, fig.width = 170, eval = FALSE}

source(file.path(wd, "figures_cleaned", "scripts", "appendix", "cascade_bonus.R"))

plot_grid(cascade_only_csdms, NULL, cascade_all_models, nrow = 1,
          labels = c("a. ", NA, "b."), label_size = 10, rel_widths= c(1,0.1,1))

```

<!---  ## ANOVA-based partitioning across species --->

```{r load_ecoregions, eval = TRUE}


source(file.path(wd, "figures_cleaned", "scripts", "ecoregions.R"))

```

```{r anova_across_species_byecoregion, fig.height = 120, fig.width = 160, fig.cap = "ANOVA-based partitioning across species", dev = "cairo_pdf", eval = TRUE}

# switch
reload_data <- FALSE

scenarios <- c("ssp245", "ssp585")
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
ecoregions <- c("Atlantic", "Boreal", "Mediterranean", "Continental", "Alpine")

csdms <- c("lasso_glm", "gam", "brt", "random_forest")
pbms <- list(abies_alba = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             fagus_sylvatica = c("expert", paste0("subset",rep(1:10, each = 10),"_rep", 1:10)),
             quercus_petraea = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             quercus_robur = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             quercus_pubescens = c("expert", paste0("subset",rep(1, each = 5),"_rep", 1:5)),
             quercus_ilex = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             betula_pendula = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             fraxinus_excelsior = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             pinus_sylvestris = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5))
             )
species_list <- names(pbms)

# empty dataframes to save intermediary outputs for some other figures
saved_data_all <- data.frame()
saved_data_species <- data.frame()
saved_data_speciesSDM <- data.frame()
saved_fit_speciesSDM <- data.frame()

# loop across the five ecoregions
for(ecoregion in ecoregions){
  
  simulations <- foreach(species = species_list, .combine=rbind) %do% {
    if(reload_data){
      
      # load simulations of PBMs
      ncores <- 3
      source(file.path(wd, "figures_cleaned", "scripts", "fig1", "load_yearly_fitness_pbm.R"))
      saveRDS(simulations_pbm, file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_", ecoregion, ".rds")))

      # load simulations of CSDMs
      source(file.path(wd, "figures_cleaned", "scripts", "fig1", "load_yearly_fitness_csdm.R"))
      saveRDS(simulations_csdm, file.path(wd,"figures_cleaned", "data", "sims", paste0("csdm_", species, "_", ecoregion, ".rds")))
      
    }else{
      simulations_pbm <- readRDS(file.path(wd, "figures_cleaned", "data", "sims", paste0("pbm_", species, "_", ecoregion, ".rds")))
      simulations_csdm <- readRDS(file.path(wd, "figures_cleaned","data", "sims", paste0("csdm_", species, "_", ecoregion, ".rds"))) 
    }
    
    # 21-year average fitness (already done for CSDM)
    simulations_pbm <- simulations_pbm %>%
      group_by(cal, gcm, ssp) %>% 
      mutate(y = rollapply(y,21,mean,align='center',fill=NA)) %>%
      ungroup %>% na.omit()
    
    # ensemble by method
    sim <- rbind(simulations_pbm, simulations_csdm)
    sim$method <- ifelse(sim$cal == "expert", "expert", 
                         ifelse(sim$cal %in% csdms, "correlative", "fitted"))
    sim <- sim %>%
      group_by(ssp, gcm, method, year) %>%
      summarise(y = mean(y), species = species) %>% ungroup()
    
    sim
  }
  
  # df <- 6 # equivalent number of degrees of freedom, if NULL => automatic
  # source(file.path(wd, "figures_updated", "scripts", "cubic_splines_wspecies.R")) # not needed anymore, we're doing the ANOVA on "raw" outputs
  source(file.path(wd, "figures_cleaned", "scripts", "fig1", "anova_across_species.R"))
  
  assign(paste0("trend_unc_", ecoregion), trend_unc)
  assign(paste0("unc_decomp_", ecoregion), unc_decomp)
  assign(paste0("unc_decomp_species_", ecoregion), unc_decomp_species)
  
}

source(file.path(wd, "figures_cleaned", "scripts", "fig1", "unctrend_plot.R"))

ecoregions_unc_trend

```

```{r anova_across_species_bycell, fig.height = 70, fig.width = 165, fig.cap = "ANOVA-based partitioning across species", dev = "cairo_pdf", eval = TRUE}

# switches
reload_data <- FALSE
reload_anova <- FALSE

scenarios <- c("ssp245", "ssp585")
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
ecoregions <- c("Atlantic", "Boreal", "Mediterranean", "Continental", "Alpine")

csdms <- c("lasso_glm", "gam", "brt", "random_forest")
pbms <- list(abies_alba = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             fagus_sylvatica = c("expert", paste0("subset",rep(1:10, each = 10),"_rep", 1:10)),
             quercus_petraea = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             quercus_robur = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             quercus_pubescens = c("expert", paste0("subset",rep(1, each = 5),"_rep", 1:5)),
             quercus_ilex = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             betula_pendula = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             fraxinus_excelsior = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             pinus_sylvestris = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5))
             )

species_list <- names(pbms)

simulations <- foreach(species = species_list, .combine=rbind) %do% {
  
    if(reload_data){
      
      # load simulations of PBMs
      ncores <- 20
      source(file.path(wd, "figures_cleaned", "scripts", "fig2", "load_yearly_fitness_pbm_bycell.R"))
      
      # load simulations of CSDMs
      source(file.path(wd, "figures_cleaned", "scripts", "fig2", "load_yearly_fitness_csdm_bycell.R"))
      
      # ensemble by method
      sim <- rbind(simulations_pbm, simulations_csdm)
      rm(simulations_pbm, simulations_csdm)
      gc(verbose = FALSE)
    
      sim$method <- ifelse(sim$cal == "expert", "expert",
                         ifelse(sim$cal %in% csdms, "correlative", "fitted"))
    
      sim <- sim %>%
        group_by(ssp, gcm, method, id_cell, x, y) %>%
        summarise(mean = mean(mean), species = species) %>% ungroup()
      gc(verbose = FALSE)
      
      saveRDS(sim, file.path(wd,"figures_cleaned","data", "sims", paste0("allsim_", species, "_", "bycell", ".rds")))
      
    }else{
      sim <- readRDS(file.path(wd,"figures_cleaned","data", "sims", paste0("allsim_", species, "_", "bycell", ".rds")))
    }
    
    sim
}
gc(verbose = FALSE)

  
if(reload_anova){
  
  ncores <- 20
  source(file.path(wd, "figures_cleaned", "scripts", "fig2", "anova_across_species_bycell.R")) 
  saveRDS(anova_ss, file.path(wd,"figures_cleaned","data", "sims", "anova_outputs_across_species_bycell.rds"))
  
}else{
  
  anova_ss <- readRDS(file.path(wd,"figures_cleaned","data", "sims", "anova_outputs_across_species_bycell.rds"))
  
}

# source(file.path(wd, "figures_updated", "scripts", "maps_uncertainties_bycell.R"))
source(file.path(wd, "figures_cleaned", "scripts", "fig2", "uncertainty_map.R"))
source(file.path(wd, "figures_cleaned", "scripts", "fig2", "suitability_map.R"))
source(file.path(wd, "figures_cleaned", "scripts", "fig2", "barplot_uncertainty_across_species.R"))

plot_grid(
    plot_grid(
        map_suitability + theme(plot.margin = margin(t=0,b=0,l=2,r=5.5)),
        map_first_source + theme(plot.margin = margin(t=0,b=0,l=5.5,r=2)), 
        align = "hv", axis = "tb", labels = c("a.", "b."), label_size = 10, vjust = 2.5, hjust = -1),
    barplot_prop_uncertainty + theme(plot.margin = margin(t=6,b=7.8,l=5.5,r=0)), 
    rel_widths = c(1, 0.35),
    labels = c("", "c."), label_size = 10, vjust = 2.5, hjust = -1)

cat("ANOVA-based partitioning across species")
knitr::kable(saved_data_all %>%
  filter(year == 2090) %>%
  mutate(climate = gcm + ssp + gcm.ssp, sdm.climate = gcm.sdm + ssp.sdm, species.all = species.sdm + species.gcm + species.ssp,
         ecoregion = factor(ecoregions, levels = c("Mediterranean", "Atlantic", "Continental", "Alpine", "Boreal"),
                            labels = c("Mediter.", "Atlantic", "Contin.", "Alpine", "Boreal"))) %>% 
  group_by(ecoregion) %>%
  summarise(sdm/tot*100, climate/tot*100, species/tot*100, species.all/tot*100))

```

<!---  ## ANOVA-based partitioning within each species --->

```{r anova_within_species_byecoregion, fig.height = 100, fig.width = 80, fig.cap = "ANOVA-based partitioning within species", dev = "cairo_pdf", eval = TRUE}

# switch
reload_data <- FALSE


# loop across the five ecoregions
data_barplot <- data.frame()
for(ecoregion in ecoregions){
  
  anova_sp <- foreach(species = species_list, .combine=rbind) %do% {
    if(reload_data){
      
      # load simulations of PBMs
      ncores <- 3
      source(file.path(wd, "figures_cleaned", "scripts", "fig1", "load_yearly_fitness_pbm.R"))
      saveRDS(simulations_pbm, file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_", ecoregion, ".rds")))

      # load simulations of CSDMs
      source(file.path(wd, "figures_cleaned", "scripts", "fig1", "load_yearly_fitness_csdm.R"))
      saveRDS(simulations_csdm, file.path(wd,"figures_cleaned", "data", "sims", paste0("csdm_", species, "_", ecoregion, ".rds")))
      
    }else{
      simulations_pbm <- readRDS(file.path(wd, "figures_cleaned", "data", "sims", paste0("pbm_", species, "_", ecoregion, ".rds")))
      simulations_csdm <- readRDS(file.path(wd, "figures_cleaned","data", "sims", paste0("csdm_", species, "_", ecoregion, ".rds"))) 
    }
    
    # 21-year average fitness (already done for CSDM)
    simulations_pbm <- simulations_pbm %>%
      group_by(cal, gcm, ssp) %>% 
      mutate(y = rollapply(y,21,mean,align='center',fill=NA)) %>%
      ungroup %>% na.omit()
    
    # ensemble by method
    sim <- rbind(simulations_pbm, simulations_csdm)
    sim$method <- ifelse(sim$cal == "expert", "expert", 
                         ifelse(sim$cal %in% csdms, "correlative", "fitted"))
    simulations <- sim %>%
      group_by(ssp, gcm, method, year) %>%
      summarise(y = mean(y), species = species) %>% ungroup()
    
    source(file.path(wd, "figures_cleaned", "scripts", "fig3", "anova_within_species.R"))
    
    anova_ss
    
  }
  
  anova_sp$ecoregion <- ecoregion
  
  data_barplot <- rbind(data_barplot, anova_sp)
  
}

data_barplot <- data_barplot %>%
    left_join(saved_data_species %>% filter(year == 2090), by = c("ecoregion", "species")) %>%
    mutate(ecoregion = factor(ecoregion, levels = rev(c("Boreal", "Alpine", "Continental", "Atlantic", "Mediterranean"))))


source(file.path(wd, "figures_cleaned", "scripts", "fig3", "barplot_uncertainty_withinspecies.R"))
# source(file.path(wd, "figures_cleaned", "scripts", "fig3", "inset_legend.R"))

barplot_prop_uncertainty_withinspecies #+
 # draw_plot(insetlegend, x = 0.78, y = .4, width = 1.2, height = .4)

cat("ANOVA-based partitioning within species")
knitr::kable(data_barplot %>%
  group_by(ecoregion, species) %>%
  reframe(sdm/tot*100, gcm/tot*100))

knitr::kable(data_barplot %>%
  group_by(ecoregion) %>%
  summarise(sdm = mean(sdm/tot*100), gcm = mean(gcm/tot*100), ssp = mean(ssp/tot*100)))

knitr::kable(data_barplot %>%
  group_by(species) %>%
  summarise(sdm = mean(sdm/tot*100), gcm = mean(gcm/tot*100), ssp = mean(ssp/tot*100)))


```

<!--- ## Distribution maps --->

```{r fagus_distributions, fig.height = 110, fig.width = 145, dev = "cairo_pdf", eval = FALSE}

plot_grid(
  plot_grid(csdm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          fpbm_dist2090 + theme(legend.position = 'none'), 
          NULL, NULL, NULL,
          ppbm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          epbm_dist2090 + theme(legend.position = 'none'),
          rel_widths = c(1,0.05,1), rel_heights = c(1,0.05,1), vjust = 3, hjust = -1,
          ncol= 3, labels = c("a. ", NA,"b.", NA, NA, NA, "c.", NA, "d."), label_size = 10),
  cowplot::get_plot_component(csdm_dist2090 + theme(legend.position = 'right'), 'guide-box-right', return_all = TRUE),
  ncol = 2, rel_widths = c(1, 0.4))


```

<!--- # Appendix --->

<!--- ## ANOVA-based fractional uncertainty --->

```{r appendix_frac_uncertainty, fig.height = 60, fig.cap = "ANOVA-based fractional uncertainty", dev = "cairo_pdf", eval = FALSE}

source(file.path(wd, "figures_cleaned", "scripts", "appendix", "fractional_uncertainty.R"))

frac_uncertainty

```

<!--- ## Decomposition of species-related interaction factors --->

```{r appendix_speciesinteractions, fig.height = 60, fig.cap = "Fractional decomposition of species-related interaction factors", dev = "cairo_pdf", eval = FALSE}


source(file.path(wd, "figures_cleaned", "scripts", "appendix", "species_interactions.R"))

unc_decomp_species


```

```{r appendix_speciesinteractions2, fig.height = 100, fig.cap = "Marginal effects", dev = "cairo_pdf", eval = FALSE}

adjusted_predictions_speciesSDM

```

<!--- ## ANOVA-based partitioning across species - with CSDM only --->

```{r anova_across_species_byecoregion_onlycsdm, fig.height =  60, fig.cap = "Fractional uncertainty - ONLY CSDM", dev = "cairo_pdf", eval = FALSE}

# switch
reload_data <- FALSE

scenarios <- c("ssp245", "ssp585")
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
ecoregions <- c("Atlantic", "Boreal", "Mediterranean", "Continental", "Alpine")

csdms <- c("lasso_glm", "gam", "brt", "random_forest")

# empty dataframes to save intermediary outputs for some other figures
saved_data_all <- data.frame()
saved_data_species <- data.frame()
saved_data_speciesSDM <- data.frame()
saved_fit_speciesSDM <- data.frame()

# loop across the five ecoregions
for(ecoregion in ecoregions){
  
  simulations <- foreach(species = species_list, .combine=rbind) %do% {
    if(reload_data){
      
      # load simulations of CSDMs
      source(file.path(wd, "figures_cleaned", "scripts", "fig1", "load_yearly_fitness_csdm.R"))
      saveRDS(simulations_csdm, file.path(wd,"figures_cleaned", "data", "sims", paste0("csdm_", species, "_", ecoregion, ".rds")))
      
    }else{

      simulations_csdm <- readRDS(file.path(wd, "figures_cleaned","data", "sims", paste0("csdm_", species, "_", ecoregion, ".rds"))) 
      
    }
    
    sim <- simulations_csdm %>%
      mutate(method = cal, species = species)
    
    sim
  }
  
  source(file.path(wd, "figures_cleaned", "scripts", "fig1", "anova_across_species.R"))
  
  assign(paste0("trend_unc_", ecoregion), trend_unc)
  assign(paste0("unc_decomp_", ecoregion), unc_decomp)
  assign(paste0("unc_decomp_species_", ecoregion), unc_decomp_species)
  
}

source(file.path(wd, "figures_cleaned", "scripts", "appendix", "fractional_uncertainty.R"))

frac_uncertainty

```

```{r anova_within_species_byecoregion_onlycsdm, fig.height = 100, fig.width = 80, fig.cap = "ANOVA-based partitioning within species - ONLY CSDM", dev = "cairo_pdf", eval = FALSE}


# loop across the five ecoregions
data_barplot <- data.frame()
for(ecoregion in ecoregions){
  
  anova_sp <- foreach(species = species_list, .combine=rbind) %do% {
    if(reload_data){

      # load simulations of CSDMs
      source(file.path(wd, "figures_cleaned", "scripts", "fig1", "load_yearly_fitness_csdm.R"))
      saveRDS(simulations_csdm, file.path(wd,"figures_cleaned", "data", "sims", paste0("csdm_", species, "_", ecoregion, ".rds")))
      
    }else{
      
      simulations_csdm <- readRDS(file.path(wd, "figures_cleaned","data", "sims", paste0("csdm_", species, "_", ecoregion, ".rds"))) 
    }
    
    simulations <- simulations_csdm %>%
      mutate(method = cal, species = species)
    
    source(file.path(wd, "figures_cleaned", "scripts", "fig3", "anova_within_species.R"))
    
    anova_ss
    
  }
  
  anova_sp$ecoregion <- ecoregion
  
  data_barplot <- rbind(data_barplot, anova_sp)
  
}

data_barplot <- data_barplot %>%
    left_join(saved_data_species %>% filter(year == 2090), by = c("ecoregion", "species")) %>%
    mutate(ecoregion = factor(ecoregion, levels = rev(c("Boreal", "Alpine", "Continental", "Atlantic", "Mediterranean"))))

source(file.path(wd, "figures_cleaned", "scripts", "fig2", "barplot_uncertainty_across_species.R"))
source(file.path(wd, "figures_cleaned", "scripts", "fig3", "barplot_uncertainty_withinspecies.R"))


barplot_prop_uncertainty_withinspecies +
  draw_plot(insetlegend, x = 0.78, y = .4, width = 1.2, height = .4) +
  scale_fill_manual(name = "", 
                    breaks = c("ssp", "gcm.ssp", "gcm", "sdm.climate", "sdm", "residuals"),
                    labels = c("SSP", "SSP - GCM", "GCM", "Climate - CSDM", "CSDM", "Residuals"),
                    values=cols)

cat("ANOVA-based partitioning within species - only CSDM")
knitr::kable(data_barplot %>%
  group_by(ecoregion, species) %>%
  reframe(sdm/tot*100, gcm/tot*100))

knitr::kable(data_barplot %>%
  group_by(ecoregion) %>%
  summarise(sdm = mean(sdm/tot*100), gcm = mean(gcm/tot*100), ssp = mean(ssp/tot*100)))

knitr::kable(data_barplot %>%
  group_by(species) %>%
  summarise(sdm = mean(sdm/tot*100), gcm = mean(gcm/tot*100), ssp = mean(ssp/tot*100)))


```

<!--- ## ANOVA-based partitioning across species - with hybrid PEM only --->

```{r anova_across_species_byecoregion_onlyhybrid, fig.height =  60, fig.cap = "Fractional uncertainty - ONLY HYBRID", dev = "cairo_pdf", eval = FALSE}

# switch
reload_data <- FALSE

scenarios <- c("ssp245", "ssp585")
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
ecoregions <- c("Atlantic", "Boreal", "Mediterranean", "Continental", "Alpine")

pbms <- list(abies_alba = c(paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             fagus_sylvatica = c(paste0("subset",rep(1:10, each = 10),"_rep", 1:10)),
             quercus_petraea = c(paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             quercus_robur = c(paste0("subset",rep(1:2, each = 5),"_rep", 1:5)),
             quercus_pubescens = c(paste0("subset",rep(1, each = 5),"_rep", 1:5)),
             quercus_ilex = c(paste0("subset",rep(1:2, each = 5),"_rep", 1:5)))
species_list <- names(pbms)

# empty dataframes to save intermediary outputs for some other figures
saved_data_all <- data.frame()
saved_data_species <- data.frame()
saved_data_speciesSDM <- data.frame()
saved_fit_speciesSDM <- data.frame()

# loop across the five ecoregions
for(ecoregion in ecoregions){
  
  simulations <- foreach(species = species_list, .combine=rbind) %do% {
    if(reload_data){
      
      # load simulations of PBMs
      ncores <- 3
      source(file.path(wd, "figures_cleaned", "scripts", "fig1", "load_yearly_fitness_pbm.R"))
      saveRDS(simulations_pbm, file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_", ecoregion, ".rds")))

    }else{
      simulations_pbm <- readRDS(file.path(wd, "figures_cleaned", "data", "sims", paste0("pbm_", species, "_", ecoregion, ".rds")))

    }
    
    # 21-year average fitness (already done for CSDM)
    simulations_pbm <- simulations_pbm %>%
      group_by(cal, gcm, ssp) %>% 
      mutate(y = rollapply(y,21,mean,align='center',fill=NA)) %>%
      ungroup %>% na.omit()
    
    # ensemble by method
    sim <- simulations_pbm %>%
      dplyr::filter(cal %in% c(paste0("subset",rep(1:2, each = 5),"_rep", 1:5))) %>%
      mutate(method = cal, species = species)
    
    sim
  }
  
  # df <- 6 # equivalent number of degrees of freedom, if NULL => automatic
  # source(file.path(wd, "figures_updated", "scripts", "cubic_splines_wspecies.R")) # not needed anymore, we're doing the ANOVA on "raw" outputs
  source(file.path(wd, "figures_cleaned", "scripts", "fig1", "anova_across_species.R"))
  
  assign(paste0("trend_unc_", ecoregion), trend_unc)
  assign(paste0("unc_decomp_", ecoregion), unc_decomp)
  assign(paste0("unc_decomp_species_", ecoregion), unc_decomp_species)
  
}

source(file.path(wd, "figures_cleaned", "scripts", "appendix", "fractional_uncertainty.R"))

frac_uncertainty

```

```{r anova_within_species_byecoregion_onlyhybrid, fig.height = 100, fig.width = 80, fig.cap = "ANOVA-based partitioning within species - ONLY HYBRID", dev = "cairo_pdf", eval = FALSE}


# loop across the five ecoregions
data_barplot <- data.frame()
for(ecoregion in ecoregions){
  
  anova_sp <- foreach(species = species_list, .combine=rbind) %do% {
    if(reload_data){
      
      # load simulations of PBMs
      ncores <- 3
      source(file.path(wd, "figures_cleaned", "scripts", "fig1", "load_yearly_fitness_pbm.R"))
      saveRDS(simulations_pbm, file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_", ecoregion, ".rds")))
      
    }else{
      simulations_pbm <- readRDS(file.path(wd, "figures_cleaned", "data", "sims", paste0("pbm_", species, "_", ecoregion, ".rds")))
    }
    
    # 21-year average fitness (already done for CSDM)
    simulations_pbm <- simulations_pbm %>%
      group_by(cal, gcm, ssp) %>% 
      mutate(y = rollapply(y,21,mean,align='center',fill=NA)) %>%
      ungroup %>% na.omit()
    
    # ensemble by method
    simulations <- simulations_pbm %>%
      dplyr::filter(cal %in% c(paste0("subset",rep(1:2, each = 5),"_rep", 1:5))) %>%
      mutate(method = cal, species = species)
    
    # 
    simulations 
    
    source(file.path(wd, "figures_cleaned", "scripts", "fig3", "anova_within_species.R"))
    
    anova_ss
    
  }
  
  anova_sp$ecoregion <- ecoregion
  
  data_barplot <- rbind(data_barplot, anova_sp)
  
}

data_barplot <- data_barplot %>%
    left_join(saved_data_species %>% filter(year == 2090), by = c("ecoregion", "species")) %>%
    mutate(ecoregion = factor(ecoregion, levels = rev(c("Boreal", "Alpine", "Continental", "Atlantic", "Mediterranean"))))

source(file.path(wd, "figures_cleaned", "scripts", "fig2", "barplot_uncertainty_across_species.R"))
source(file.path(wd, "figures_cleaned", "scripts", "fig3", "barplot_uncertainty_withinspecies.R"))


barplot_prop_uncertainty_withinspecies +
  draw_plot(insetlegend, x = 0.78, y = .4, width = 1.2, height = .4) +
  scale_fill_manual(name = "", 
                    breaks = c("ssp", "gcm.ssp", "gcm", "sdm.climate", "sdm", "residuals"),
                    labels = c("SSP", "SSP - GCM", "GCM", "Climate - CSDM", "CSDM", "Residuals"),
                    values=cols)

cat("ANOVA-based partitioning within species - only hybrid")
knitr::kable(data_barplot %>%
  group_by(ecoregion, species) %>%
  reframe(sdm/tot*100, gcm/tot*100))

knitr::kable(data_barplot %>%
  group_by(ecoregion) %>%
  summarise(sdm = mean(sdm/tot*100), gcm = mean(gcm/tot*100), ssp = mean(ssp/tot*100)))

knitr::kable(data_barplot %>%
  group_by(species) %>%
  summarise(sdm = mean(sdm/tot*100), gcm = mean(gcm/tot*100), ssp = mean(ssp/tot*100)))


```

<!--- ## Spatial disagreement within model class, Fagus sylvatica --->

```{r model_disagreement_withinclass, fig.height = 80, fig.width = 80, fig.cap = "Spatial disagreement within model class, Fagus sylvatica", dev = "cairo_pdf", eval = FALSE}

source(file.path(wd, "figures_cleaned", "scripts", "appendix", "model_disagreement_withinclass.R"))

map_disag_withinclass

```

<!---  ## Quercus robur divergent simulations --->

```{r quercusrobur_fittedPEM_simulations, dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "quercus_robur"

nsim <- 50
breakseq <- seq(0, nsim, 10)

calibrations <- (paste0("subset",rep(1:2, each = 5),"_rep", 1:5))
type <- "fitted"
ncores <- 10

# load simulations
if(reload_data){
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_pbm_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_distribution_", scenario, ".rds")))
  sim_dist_2090 <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
}

# fitness maps
panel_color <- "#995D81"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))

fpbm_fit2050 <- fitness_map_2050
fpbm_fit2090 <- fitness_map_2090
fpbm_dist2090 <- dist_map_lessmore
fpbm_agreement <- sim_agreement

```

```{r quercusrobur_expertPEM_simulations, dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "quercus_robur"

nsim <- 5
breakseq <- seq(0, nsim, 1)

calibrations <- 'expert'
type <- 'expert'
ncores <- 1

# load simulations
if(reload_data){
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_pbm_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_distribution_", scenario, ".rds")))
  sim_dist_2090 <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
}

# fitness maps
panel_color <- "#018530"
# panel_color <- "grey80"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))

epbm_fit2050 <- fitness_map_2050
epbm_fit2090 <- fitness_map_2090
epbm_dist2090 <- dist_map_lessmore
epbm_agreement <- sim_agreement

```

```{r quercusrobur_CSDM_simulations, dev = "cairo_pdf", eval = FALSE}

nsim <- 20
breakseq <- seq(0, nsim, 1)

models <- c("lasso_glm", "random_forest", "gam", "brt")
species <- "quercus_robur"

# load simulations
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_csdm_maps.R"))

crs(sim_fitness) <- "EPSG:4326"
crs(sim_distribution) <- "EPSG:4326"
crs(sim_agreement) <- "EPSG:4326"

# fitness maps
panel_color <- "#457b9d"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))
csdm_dist2090 <- dist_map_lessmore

csdm_fit2050 <- fitness_map_2050
csdm_fit2090 <- fitness_map_2090

csdm_agreement <- sim_agreement

```

```{r quercusrobur_cascade, fig.height = 120, fig.width = 180, fig.cap = "Quercus robur, ssp2", dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 
target_ext <- ext(-10.5, 31.7, 34.6, 71.2)
ytext <- 0.4

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "quercus_robur"

csdms <- c("lasso_glm", "gam", "brt", "random_forest")
pbms <- list(quercus_robur = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)))

# load simulations
if(reload_data){
  # load simulations of PBMs
  ncores <- 5
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_yearly_fitness_pbm_all.R"))
  saveRDS(simulations_pbm, file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_Europe", ".rds")))

  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_yearly_fitness_csdm_all.R"))
  saveRDS(simulations_csdm, file.path(wd,"figures_cleaned","data", "sims", paste0("csdm_", species, "_Europe", ".rds")))
  
}else{
  simulations_pbm <- readRDS(file = file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_Europe", ".rds")))
  simulations_csdm <- readRDS(file = file.path(wd,"figures_cleaned","data", "sims", paste0("csdm_", species, "_Europe", ".rds")))
}

simulations <- rbind(simulations_pbm,simulations_csdm)

source(file.path(wd, "figures_cleaned", "scripts", "fig4", "uncertainty_cascade.R"))

plot_grid(
  plot_grid(epbm_fit2050 + theme(legend.position = 'none'), 
            fpbm_fit2050 + theme(legend.position = 'none'), 
            csdm_fit2050 + theme(legend.position = 'none'),
            ncol = 1),
  NULL,
  plot_grid(NULL, plot_grid(cascade1, NULL, cascade2, nrow = 1, rel_widths = c(1.1,-0.1,1)), 
            NULL,
            cowplot::get_plot_component(cascade2 + theme(legend.position = 'bottom'), 'guide-box-bottom', return_all = TRUE), 
            cowplot::get_plot_component(fpbm_fit2090, 'guide-box-bottom', return_all = TRUE), 
            ncol = 1, rel_heights = c(1.4,5, 0.8, 0.7, 0.7)),
  NULL,
  plot_grid(epbm_fit2090 + theme(legend.position = 'none'), 
            fpbm_fit2090 + theme(legend.position = 'none'), 
            csdm_fit2090 + theme(legend.position = 'none'),
            ncol = 1),
  ncol = 5, rel_widths = c(1, -0.1, 1.1, -0.1, 1)) +
  draw_text("2040-2060", x = 2/5, y = 4/5+0.05, size = 8) +
  draw_text("2080-2100", x = 3/5, y = 4/5+0.05, size = 8) +
  draw_text("Projected change in suitability\nrelative to 1970-2000", x = 1/2, y = 1/5+0.03, size = 7.5)
  

```

```{r quercusrobur_distributions, fig.height = 55, fig.width = 195, dev = "cairo_pdf", eval = FALSE, fig.cap = "Q. robur distribution"}

plot_grid(
  plot_grid(csdm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          fpbm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          epbm_dist2090 + theme(legend.position = 'none'),
          rel_widths = c(1,0.05,1,0.05,1), vjust = 2, hjust = -1,
          nrow = 1, labels = c("a. ", NA,"b.", NA, "c."), label_size = 10),
  cowplot::get_plot_component(csdm_dist2090 + theme(legend.position = 'right'), 'guide-box-right', return_all = TRUE),
  ncol = 2, rel_widths = c(1, 0.18))


```

<!---  ## Quercus petraea divergent simulations --->

```{r quercuspetraea_fittedPEM_simulations, dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "quercus_petraea"

nsim <- 50
breakseq <- seq(0, nsim, 10)

calibrations <- (paste0("subset",rep(1:2, each = 5),"_rep", 1:5))
type <- "fitted"
ncores <- 10

# load simulations
if(reload_data){
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_pbm_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_distribution_", scenario, ".rds")))
  sim_dist_2090 <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
}

# fitness maps
panel_color <- "#995D81"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))
fpbm_dist2090 <- dist_map_lessmore

fpbm_fit2050 <- fitness_map_2050
fpbm_fit2090 <- fitness_map_2090

fpbm_agreement <- sim_agreement

```

```{r quercuspetraea_expertPEM_simulations, dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "quercus_petraea"

nsim <- 5
breakseq <- seq(0, nsim, 1)

calibrations <- 'expert'
type <- 'expert'
ncores <- 1

# load simulations
if(reload_data){
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_pbm_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_distribution_", scenario, ".rds")))
  sim_dist_2090 <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
}

# fitness maps
panel_color <- "#018530"
# panel_color <- "grey80"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))
epbm_dist2090 <- dist_map_lessmore

epbm_fit2050 <- fitness_map_2050
epbm_fit2090 <- fitness_map_2090

epbm_agreement <- sim_agreement

```

```{r quercuspetraea_CSDM_simulations, dev = "cairo_pdf", eval = FALSE}

nsim <- 20
breakseq <- seq(0, nsim, 1)

models <- c("lasso_glm", "random_forest", "gam", "brt")

# load simulations
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_csdm_maps.R"))

crs(sim_fitness) <- "EPSG:4326"
crs(sim_distribution) <- "EPSG:4326"
crs(sim_agreement) <- "EPSG:4326"

# fitness maps
panel_color <- "#457b9d"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))
csdm_dist2090 <- dist_map_lessmore

csdm_fit2050 <- fitness_map_2050
csdm_fit2090 <- fitness_map_2090

csdm_agreement <- sim_agreement

```

```{r quercuspetraea_cascade, fig.height = 120, fig.width = 180, fig.cap = "Quercus petraea, ssp2", dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 
target_ext <- ext(-10.5, 31.7, 34.6, 71.2)
ytext <- 0.4

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "quercus_petraea"

csdms <- c("lasso_glm", "gam", "brt", "random_forest")
pbms <- list(quercus_petraea = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)))

# load simulations
if(reload_data){
  # load simulations of PBMs
  ncores <- 5
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_yearly_fitness_pbm_all.R"))
  saveRDS(simulations_pbm, file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_Europe", ".rds")))

  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_yearly_fitness_csdm_all.R"))
  saveRDS(simulations_csdm, file.path(wd,"figures_cleaned","data", "sims", paste0("csdm_", species, "_Europe", ".rds")))
  
}else{
  simulations_pbm <- readRDS(file = file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_Europe", ".rds")))
  simulations_csdm <- readRDS(file = file.path(wd,"figures_cleaned","data", "sims", paste0("csdm_", species, "_Europe", ".rds")))
}

simulations <- rbind(simulations_pbm,simulations_csdm)

source(file.path(wd, "figures_cleaned", "scripts", "fig4", "uncertainty_cascade.R"))

plot_grid(
  plot_grid(epbm_fit2050 + theme(legend.position = 'none'), 
            fpbm_fit2050 + theme(legend.position = 'none'), 
            csdm_fit2050 + theme(legend.position = 'none'),
            ncol = 1),
  NULL,
  plot_grid(NULL, plot_grid(cascade1, NULL, cascade2, nrow = 1, rel_widths = c(1.1,-0.1,1)), 
            NULL,
            cowplot::get_plot_component(cascade2 + theme(legend.position = 'bottom'), 'guide-box-bottom', return_all = TRUE), 
            cowplot::get_plot_component(fpbm_fit2090, 'guide-box-bottom', return_all = TRUE), 
            ncol = 1, rel_heights = c(1.4,5, 0.8, 0.7, 0.7)),
  NULL,
  plot_grid(epbm_fit2090 + theme(legend.position = 'none'), 
            fpbm_fit2090 + theme(legend.position = 'none'), 
            csdm_fit2090 + theme(legend.position = 'none'),
            ncol = 1),
  ncol = 5, rel_widths = c(1, -0.1, 1.1, -0.1, 1)) +
  draw_text("2040-2060", x = 2/5, y = 4/5+0.05, size = 8) +
  draw_text("2080-2100", x = 3/5, y = 4/5+0.05, size = 8) +
  draw_text("Projected change in suitability\nrelative to 1970-2000", x = 1/2, y = 1/5+0.03, size = 7.5)
  

```

```{r quercuspetraea_distributions, fig.height = 55, fig.width = 195, dev = "cairo_pdf", eval = FALSE, fig.cap = "Q. petraea distribution"}

plot_grid(
  plot_grid(csdm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          fpbm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          epbm_dist2090 + theme(legend.position = 'none'),
          rel_widths = c(1,0.05,1,0.05,1), vjust = 2, hjust = -1,
          nrow = 1, labels = c("a. ", NA,"b.", NA, "c."), label_size = 10),
  cowplot::get_plot_component(csdm_dist2090 + theme(legend.position = 'right'), 'guide-box-right', return_all = TRUE),
  ncol = 2, rel_widths = c(1, 0.18))


```

<!---  ## Quercus ilex divergent simulations --->

```{r quercusilex_fittedPEM_simulations, dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "quercus_ilex"

nsim <- 50
breakseq <- seq(0, nsim, 10)

calibrations <- (paste0("subset",rep(1:2, each = 5),"_rep", 1:5))
type <- "fitted"
ncores <- 10

# load simulations
if(reload_data){
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_pbm_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_distribution_", scenario, ".rds")))
  sim_dist_2090 <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
}

# fitness maps
panel_color <- "#995D81"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))
fpbm_dist2090 <- dist_map_lessmore

fpbm_fit2050 <- fitness_map_2050
fpbm_fit2090 <- fitness_map_2090

fpbm_agreement <- sim_agreement

```

```{r quercusilex_expertPEM_simulations, dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "quercus_ilex"

nsim <- 5
breakseq <- seq(0, nsim, 1)

calibrations <- 'expert'
type <- 'expert'
ncores <- 1

# load simulations
if(reload_data){
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_pbm_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_distribution_", scenario, ".rds")))
  sim_dist_2090 <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
}

# fitness maps
panel_color <- "#018530"
# panel_color <- "grey80"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))
epbm_dist2090 <- dist_map_lessmore

epbm_fit2050 <- fitness_map_2050
epbm_fit2090 <- fitness_map_2090

epbm_agreement <- sim_agreement

```

```{r quercusilex_CSDM_simulations, dev = "cairo_pdf", eval = FALSE}

nsim <- 20
breakseq <- seq(0, nsim, 1)

models <- c("lasso_glm", "random_forest", "gam", "brt")

# load simulations
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_csdm_maps.R"))

crs(sim_fitness) <- "EPSG:4326"
crs(sim_distribution) <- "EPSG:4326"
crs(sim_agreement) <- "EPSG:4326"

# fitness maps
panel_color <- "#457b9d"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))
csdm_dist2090 <- dist_map_lessmore

csdm_fit2050 <- fitness_map_2050
csdm_fit2090 <- fitness_map_2090

csdm_agreement <- sim_agreement

```

```{r quercusilex_cascade, fig.height = 120, fig.width = 180, fig.cap = "Quercus ilex, ssp2", dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 
target_ext <- ext(-10.5, 31.7, 34.6, 71.2)
ytext <- -0.15

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "quercus_ilex"

csdms <- c("lasso_glm", "gam", "brt", "random_forest")
pbms <- list(quercus_ilex = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)))

# load simulations
if(reload_data){
  # load simulations of PBMs
  ncores <- 5
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_yearly_fitness_pbm_all.R"))
  saveRDS(simulations_pbm, file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_Europe", ".rds")))

  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_yearly_fitness_csdm_all.R"))
  saveRDS(simulations_csdm, file.path(wd,"figures_cleaned","data", "sims", paste0("csdm_", species, "_Europe", ".rds")))
  
}else{
  simulations_pbm <- readRDS(file = file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_Europe", ".rds")))
  simulations_csdm <- readRDS(file = file.path(wd,"figures_cleaned","data", "sims", paste0("csdm_", species, "_Europe", ".rds")))
}

simulations <- rbind(simulations_pbm,simulations_csdm)

source(file.path(wd, "figures_cleaned", "scripts", "fig4", "uncertainty_cascade.R"))

plot_grid(
  plot_grid(epbm_fit2050 + theme(legend.position = 'none'), 
            fpbm_fit2050 + theme(legend.position = 'none'), 
            csdm_fit2050 + theme(legend.position = 'none'),
            ncol = 1),
  NULL,
  plot_grid(NULL, plot_grid(cascade1, NULL, cascade2, nrow = 1, rel_widths = c(1.1,-0.1,1)), 
            NULL,
            cowplot::get_plot_component(cascade2 + theme(legend.position = 'bottom'), 'guide-box-bottom', return_all = TRUE), 
            cowplot::get_plot_component(fpbm_fit2090, 'guide-box-bottom', return_all = TRUE), 
            ncol = 1, rel_heights = c(1.4,5, 0.8, 0.7, 0.7)),
  NULL,
  plot_grid(epbm_fit2090 + theme(legend.position = 'none'), 
            fpbm_fit2090 + theme(legend.position = 'none'), 
            csdm_fit2090 + theme(legend.position = 'none'),
            ncol = 1),
  ncol = 5, rel_widths = c(1, -0.1, 1.1, -0.1, 1)) +
  draw_text("2040-2060", x = 2/5, y = 4/5+0.05, size = 8) +
  draw_text("2080-2100", x = 3/5, y = 4/5+0.05, size = 8) +
  draw_text("Projected change in suitability\nrelative to 1970-2000", x = 1/2, y = 1/5+0.03, size = 7.5)
  

```

```{r quercusilex_distributions, fig.height = 55, fig.width = 195, dev = "cairo_pdf", eval = FALSE, fig.cap = "Q. ilex distribution"}

plot_grid(
  plot_grid(csdm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          fpbm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          epbm_dist2090 + theme(legend.position = 'none'),
          rel_widths = c(1,0.05,1,0.05,1), vjust = 2, hjust = -1,
          nrow = 1, labels = c("a. ", NA,"b.", NA, "c."), label_size = 10),
  cowplot::get_plot_component(csdm_dist2090 + theme(legend.position = 'right'), 'guide-box-right', return_all = TRUE),
  ncol = 2, rel_widths = c(1, 0.18))


```

<!---  ## Quercus pubescens divergent simulations --->

```{r quercuspubescens_fittedPEM_simulations, dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "quercus_pubescens"

nsim <- 25
breakseq <- seq(0, nsim, 5)

calibrations <- (paste0("subset",rep(1, each = 5),"_rep", 1:5))
type <- "fitted"
ncores <- 10

# load simulations
if(reload_data){
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_pbm_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_distribution_", scenario, ".rds")))
  sim_dist_2090 <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
}

# fitness maps
panel_color <- "#995D81"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))
fpbm_dist2090 <- dist_map_lessmore

fpbm_fit2050 <- fitness_map_2050
fpbm_fit2090 <- fitness_map_2090

fpbm_agreement <- sim_agreement

```

```{r quercuspubescens_expertPEM_simulations, dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "quercus_pubescens"

nsim <- 5
breakseq <- seq(0, nsim, 1)

calibrations <- 'expert'
type <- 'expert'
ncores <- 1

# load simulations
if(reload_data){
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_pbm_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_distribution_", scenario, ".rds")))
  sim_dist_2090 <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
}

# fitness maps
panel_color <- "#018530"
# panel_color <- "grey80"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))
epbm_dist2090 <- dist_map_lessmore

epbm_fit2050 <- fitness_map_2050
epbm_fit2090 <- fitness_map_2090

epbm_agreement <- sim_agreement

```

```{r quercuspubescens_CSDM_simulations, dev = "cairo_pdf", eval = FALSE}

nsim <- 20
breakseq <- seq(0, nsim, 1)

models <- c("lasso_glm", "random_forest", "gam", "brt")

# load simulations
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_csdm_maps.R"))

crs(sim_fitness) <- "EPSG:4326"
crs(sim_distribution) <- "EPSG:4326"
crs(sim_agreement) <- "EPSG:4326"

# fitness maps
panel_color <- "#457b9d"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))
csdm_dist2090 <- dist_map_lessmore

csdm_fit2050 <- fitness_map_2050
csdm_fit2090 <- fitness_map_2090

csdm_agreement <- sim_agreement

```

```{r quercuspubescens_cascade, fig.height = 120, fig.width = 180, fig.cap = "Quercus pubescens, ssp2", dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 
target_ext <- ext(-10.5, 31.7, 34.6, 71.2)
ytext <- -0.15

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "quercus_pubescens"

csdms <- c("lasso_glm", "gam", "brt", "random_forest")
pbms <- list(quercus_pubescens = c("expert", paste0("subset",rep(1, each = 5),"_rep", 1:5)))

# load simulations
if(reload_data){
  # load simulations of PBMs
  ncores <- 5
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_yearly_fitness_pbm_all.R"))
  saveRDS(simulations_pbm, file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_Europe", ".rds")))

  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_yearly_fitness_csdm_all.R"))
  saveRDS(simulations_csdm, file.path(wd,"figures_cleaned","data", "sims", paste0("csdm_", species, "_Europe", ".rds")))
  
}else{
  simulations_pbm <- readRDS(file = file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_Europe", ".rds")))
  simulations_csdm <- readRDS(file = file.path(wd,"figures_cleaned","data", "sims", paste0("csdm_", species, "_Europe", ".rds")))
}

simulations <- rbind(simulations_pbm,simulations_csdm)

source(file.path(wd, "figures_cleaned", "scripts", "fig4", "uncertainty_cascade.R"))

plot_grid(
  plot_grid(epbm_fit2050 + theme(legend.position = 'none'), 
            fpbm_fit2050 + theme(legend.position = 'none'), 
            csdm_fit2050 + theme(legend.position = 'none'),
            ncol = 1),
  NULL,
  plot_grid(NULL, plot_grid(cascade1, NULL, cascade2, nrow = 1, rel_widths = c(1.1,-0.1,1)), 
            NULL,
            cowplot::get_plot_component(cascade2 + theme(legend.position = 'bottom'), 'guide-box-bottom', return_all = TRUE), 
            cowplot::get_plot_component(fpbm_fit2090, 'guide-box-bottom', return_all = TRUE), 
            ncol = 1, rel_heights = c(1.4,5, 0.8, 0.7, 0.7)),
  NULL,
  plot_grid(epbm_fit2090 + theme(legend.position = 'none'), 
            fpbm_fit2090 + theme(legend.position = 'none'), 
            csdm_fit2090 + theme(legend.position = 'none'),
            ncol = 1),
  ncol = 5, rel_widths = c(1, -0.1, 1.1, -0.1, 1)) +
  draw_text("2040-2060", x = 2/5, y = 4/5+0.05, size = 8) +
  draw_text("2080-2100", x = 3/5, y = 4/5+0.05, size = 8) +
  draw_text("Projected change in suitability\nrelative to 1970-2000", x = 1/2, y = 1/5+0.03, size = 7.5)
  

```

```{r quercuspubescens_distributions, fig.height = 55, fig.width = 195, dev = "cairo_pdf", eval = FALSE, fig.cap = "Q. pubescens distribution"}

plot_grid(
  plot_grid(csdm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          fpbm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          epbm_dist2090 + theme(legend.position = 'none'),
          rel_widths = c(1,0.05,1,0.05,1), vjust = 2, hjust = -1,
          nrow = 1, labels = c("a. ", NA,"b.", NA, "c."), label_size = 10),
  cowplot::get_plot_component(csdm_dist2090 + theme(legend.position = 'right'), 'guide-box-right', return_all = TRUE),
  ncol = 2, rel_widths = c(1, 0.18))


```

<!---  ## Abies alba divergent simulations --->

```{r abiesalba_fittedPEM_simulations, dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "abies_alba"

nsim <- 50
breakseq <- seq(0, nsim, 10)

calibrations <- (paste0("subset",rep(1:2, each = 5),"_rep", 1:5))
type <- "fitted"
ncores <- 10

# load simulations
if(reload_data){
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_pbm_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_distribution_", scenario, ".rds")))
  sim_dist_2090 <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
}

# fitness maps
panel_color <- "#995D81"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))
fpbm_dist2090 <- dist_map_lessmore

fpbm_fit2050 <- fitness_map_2050
fpbm_fit2090 <- fitness_map_2090

fpbm_agreement <- sim_agreement

```

```{r abiesalba_expertPEM_simulations, dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "abies_alba"

nsim <- 5
breakseq <- seq(0, nsim, 1)

calibrations <- 'expert'
type <- 'expert'
ncores <- 1

# load simulations
if(reload_data){
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_pbm_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd, "figures_cleaned", "data", "maps", paste0(species, "_", type, "_distribution_", scenario, ".rds")))
  sim_dist_2090 <- readRDS(file = file.path(wd,"figures_cleaned","data","maps", paste0(species, "_", type, "_2090_dist_", scenario, ".rds")))
}

# fitness maps
panel_color <- "#018530"
# panel_color <- "grey80"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))
epbm_dist2090 <- dist_map_lessmore

epbm_fit2050 <- fitness_map_2050
epbm_fit2090 <- fitness_map_2090

epbm_agreement <- sim_agreement

```

```{r abiesalba_CSDM_simulations, dev = "cairo_pdf", eval = FALSE}

nsim <- 20
breakseq <- seq(0, nsim, 1)

models <- c("lasso_glm", "random_forest", "gam", "brt")

# load simulations
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_csdm_maps.R"))

crs(sim_fitness) <- "EPSG:4326"
crs(sim_distribution) <- "EPSG:4326"
crs(sim_agreement) <- "EPSG:4326"

# fitness maps
panel_color <- "#457b9d"
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "fitness_maps_wagreement.R"))

# distribution map
source(file.path(wd, "figures_cleaned", "scripts", "fig4", "distribution_map.R"))
csdm_dist2090 <- dist_map_lessmore

csdm_fit2050 <- fitness_map_2050
csdm_fit2090 <- fitness_map_2090

csdm_agreement <- sim_agreement

```

```{r abiesalba_cascade, fig.height = 120, fig.width = 180, fig.cap = "Abies alba, ssp2", dev = "cairo_pdf", eval = FALSE}

#switch
reload_data <- FALSE 
target_ext <- ext(-10.5, 31.7, 34.6, 71.2)
ytext <- 0.40

gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")
scenario <- "ssp245"
baseline <- 1970:2000 # define temporal baseline (= reference)
years <- c(2050, 2090)

species <- "abies_alba"

csdms <- c("lasso_glm", "gam", "brt", "random_forest")
pbms <- list(abies_alba = c("expert", paste0("subset",rep(1:2, each = 5),"_rep", 1:5)))

# load simulations
if(reload_data){
  # load simulations of PBMs
  ncores <- 5
  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_yearly_fitness_pbm_all.R"))
  saveRDS(simulations_pbm, file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_Europe", ".rds")))

  source(file.path(wd, "figures_cleaned", "scripts", "fig4", "load_yearly_fitness_csdm_all.R"))
  saveRDS(simulations_csdm, file.path(wd,"figures_cleaned","data", "sims", paste0("csdm_", species, "_Europe", ".rds")))
  
}else{
  simulations_pbm <- readRDS(file = file.path(wd,"figures_cleaned","data", "sims", paste0("pbm_", species, "_Europe", ".rds")))
  simulations_csdm <- readRDS(file = file.path(wd,"figures_cleaned","data", "sims", paste0("csdm_", species, "_Europe", ".rds")))
}

simulations <- rbind(simulations_pbm,simulations_csdm)

source(file.path(wd, "figures_cleaned", "scripts", "fig4", "uncertainty_cascade.R"))

plot_grid(
  plot_grid(epbm_fit2050 + theme(legend.position = 'none'), 
            fpbm_fit2050 + theme(legend.position = 'none'), 
            csdm_fit2050 + theme(legend.position = 'none'),
            ncol = 1),
  NULL,
  plot_grid(NULL, plot_grid(cascade1, NULL, cascade2, nrow = 1, rel_widths = c(1.1,-0.1,1)), 
            NULL,
            cowplot::get_plot_component(cascade2 + theme(legend.position = 'bottom'), 'guide-box-bottom', return_all = TRUE), 
            cowplot::get_plot_component(fpbm_fit2090, 'guide-box-bottom', return_all = TRUE), 
            ncol = 1, rel_heights = c(1.4,5, 0.8, 0.7, 0.7)),
  NULL,
  plot_grid(epbm_fit2090 + theme(legend.position = 'none'), 
            fpbm_fit2090 + theme(legend.position = 'none'), 
            csdm_fit2090 + theme(legend.position = 'none'),
            ncol = 1),
  ncol = 5, rel_widths = c(1, -0.1, 1.1, -0.1, 1)) +
  draw_text("2040-2060", x = 2/5, y = 4/5+0.05, size = 8) +
  draw_text("2080-2100", x = 3/5, y = 4/5+0.05, size = 8) +
  draw_text("Projected change in suitability\nrelative to 1970-2000", x = 1/2, y = 1/5+0.03, size = 7.5)
  

```

```{r abiesalba_distributions, fig.height = 55, fig.width = 195, dev = "cairo_pdf", eval = FALSE, fig.cap = "A. alba distribution"}

plot_grid(
  plot_grid(csdm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          fpbm_dist2090 + theme(legend.position = 'none'), 
          NULL,
          epbm_dist2090 + theme(legend.position = 'none'),
          rel_widths = c(1,0.05,1,0.05,1), vjust = 2, hjust = -1,
          nrow = 1, labels = c("a. ", NA,"b.", NA, "c."), label_size = 10),
  cowplot::get_plot_component(csdm_dist2090 + theme(legend.position = 'right'), 'guide-box-right', return_all = TRUE),
  ncol = 2, rel_widths = c(1, 0.18))


```