---
title: "Figures"
author: "Victor Van der Meersch"
date: "2024-04-22"
geometry: "left=2.5cm,right=2.5cm,top=2cm,bottom=2cm"
output: pdf_document
---

```{r setup, include=FALSE}
wd <- "C:/Users/vandermeersch/Documents/CEFE/projects/future_forests"

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.path= paste0(wd, "/figures/files/"))
chunkhooks::hook_figure_unit("mm")

library(terra)
library(sf)
library(dplyr)
library(rnaturalearth)
library(lubridate)
library(cowplot)
library(zoo)
library(ggplot2)
library(future.apply)
library(doFuture)
library(tidyterra)
library(ggpattern)
library(RColorBrewer)
library(khroma)
```

## Global - Fagus sylvatica

```{r global_fitness_ssp245, fig.height = 75, fig.cap = "Fitness change, relative to 1970-2000.", dev = "cairo_pdf"}
reload_data <- TRUE
breakseq <- seq(0, 500, 100)

species <- "fagus_sylvatica"
baseline <- 1970:2000 # define temporal baseline (= reference)
calibrations <- (paste0("subset",rep(1:10, each = 10),"_rep", 1:10))
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")

scenario <- "ssp245"
years <- c(2030, 2070, 2090)

# load simulations
if(reload_data){
  source(file.path(wd, "figures", "scripts", "load_invcal_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd,"figures","data","maps", species, "fitted", paste0("fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd,"figures","data","maps", species, "fitted", paste0("agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd,"figures","data","maps", species, "fitted", paste0("distribution_", scenario, ".rds")))
}

# process maps
source(file.path(wd, "figures", "scripts", "fitness_maps_wagreement.R"))


```

```{r global_distribution_ssp245, fig.height = 130, fig.cap = "Fitness change relative to 1970-2000 + range shifts (SSP245)", dev = "cairo_pdf"}

# process maps
source(file.path(wd, "figures", "scripts", "distribution_maps.R"))
plot_grid(fitness_maps, distribution_maps, nrow = 2, rel_heights = c(1,1))

```

```{r global_fitness_ssp585, fig.height = 75, fig.cap = "Fitness change, relative to 1970-2000.", dev = "cairo_pdf"}
reload_data <- TRUE

species <- "fagus_sylvatica"
baseline <- 1970:2000 # define temporal baseline (= reference)
calibrations <- (paste0("subset",rep(1:10, each = 10),"_rep", 1:10))
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")

scenario <- "ssp585"

# load simulations
if(reload_data){
  source(file.path(wd, "figures", "scripts", "load_invcal_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd,"figures","data","maps", species, "fitted", paste0("fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd,"figures","data","maps", species, "fitted", paste0("agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd,"figures","data","maps", species, "fitted", paste0("distribution_", scenario, ".rds")))
}

# process maps
source(file.path(wd, "figures", "scripts", "fitness_maps_wagreement.R"))

```

```{r global_distribution_ssp585, fig.height = 130, fig.cap = "Fitness change relative to 1970-2000 + range shifts (SSP585)", dev = "cairo_pdf"}

# process maps
source(file.path(wd, "figures", "scripts", "distribution_maps.R"))
plot_grid(fitness_maps, distribution_maps,nrow = 2, rel_heights = c(1,1))

```

```{r global_fitness_ssp245_fsyl_expert, fig.height = 75, fig.cap = "EXPERT CALIBRATION. Fitness change, relative to 1970-2000.", dev = "cairo_pdf"}
reload_data <- TRUE
breakseq <- seq(0, 5, 1)

species <- "fagus_sylvatica"
baseline <- 1970:2000 # define temporal baseline (= reference)
calibrations <- "expert"
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")

scenario <- "ssp245"

# load simulations
if(reload_data){
  source(file.path(wd, "figures", "scripts", "load_exp_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd,"figures","data","maps", species, "expert", paste0("fitness_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd,"figures","data","maps", species, "expert", paste0("distribution_", scenario, ".rds")))
}

# process maps
source(file.path(wd, "figures", "scripts", "fitness_maps.R"))

```

```{r global_distribution_ssp245_expert, fig.height = 130, fig.cap = "EXPERT CALIBRATION. Fitness change relative to 1970-2000 + range shifts (SSP245)", dev = "cairo_pdf"}

# process maps
source(file.path(wd, "figures", "scripts", "distribution_maps.R"))
plot_grid(fitness_maps, distribution_maps,nrow = 2, rel_heights = c(1,1))

```

```{r global_fitness_ssp585_fsyl_expert, fig.height = 75, fig.cap = "EXPERT CALIBRATION. Fitness change, relative to 1970-2000.", dev = "cairo_pdf"}
reload_data <- TRUE
breakseq <- seq(0, 5, 1)

species <- "fagus_sylvatica"
baseline <- 1970:2000 # define temporal baseline (= reference)
calibrations <- "expert"
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")

scenario <- "ssp585"

# load simulations
if(reload_data){
  source(file.path(wd, "figures", "scripts", "load_exp_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd,"figures","data","maps", species, "expert", paste0("fitness_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd,"figures","data","maps", species, "expert", paste0("distribution_", scenario, ".rds")))
}

# process maps
source(file.path(wd, "figures", "scripts", "fitness_maps.R"))

```

```{r global_distribution_ssp585_expert, fig.height = 130, fig.cap = "EXPERT CALIBRATION. Fitness change relative to 1970-2000 + range shifts (SSP585)", dev = "cairo_pdf"}

# process maps
source(file.path(wd, "figures", "scripts", "distribution_maps.R"))
plot_grid(fitness_maps, distribution_maps,nrow = 2, rel_heights = c(1,1))

```

```{r global_fitness_ssp245_fsyl_csdm, fig.height = 75, fig.cap = "CSDM. Fitness change, relative to 1970-2000.", dev = "cairo_pdf"}

breakseq <- seq(0, 20, 5)

species <- "fagus_sylvatica"
models <- c("lasso_glm", "random_forest", "gam", "brt")
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")

scenario <- "ssp245"

# load simulations
source(file.path(wd, "figures", "scripts", "load_csdm_maps.R"))

crs(sim_fitness) <- "EPSG:4326"
crs(sim_distribution) <- "EPSG:4326"
crs(sim_agreement) <- "EPSG:4326"

# process maps
source(file.path(wd, "figures", "scripts", "fitness_maps_wagreement.R"))

```

```{r global_distribution_ssp245_fsyl_csdm, fig.height = 130, fig.cap = "CSDM. Fitness change relative to 1970-2000 + range shifts (SSP245)", dev = "cairo_pdf"}

# process maps
source(file.path(wd, "figures", "scripts", "distribution_maps.R"))
plot_grid(fitness_maps, distribution_maps,nrow = 2, rel_heights = c(1,1))

```

```{r global_fitness_ssp585_fsyl_csdm, fig.height = 75, fig.cap = "CSDM. Fitness change, relative to 1970-2000.", dev = "cairo_pdf"}

breakseq <- seq(0, 20, 5)

species <- "fagus_sylvatica"
models <- c("lasso_glm", "random_forest", "gam", "brt")
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")

scenario <- "ssp585"

# load simulations
source(file.path(wd, "figures", "scripts", "load_csdm_maps.R"))

crs(sim_fitness) <- "EPSG:4326"
crs(sim_distribution) <- "EPSG:4326"
crs(sim_agreement) <- "EPSG:4326"

# process maps
source(file.path(wd, "figures", "scripts", "fitness_maps_wagreement.R"))

```

```{r global_distribution_ssp585_fsyl_csdm, fig.height = 130, fig.cap = "CSDM. Fitness change relative to 1970-2000 + range shifts (SSP585)", dev = "cairo_pdf"}

# process maps
source(file.path(wd, "figures", "scripts", "distribution_maps.R"))
plot_grid(fitness_maps, distribution_maps,nrow = 2, rel_heights = c(1,1))

```

\newpage 

# Global - Quercus robur

```{r global_fitness_ssp245_qrob, fig.height = 75, fig.cap = "Fitness change, relative to 1970-2000.", dev = "cairo_pdf", eval = TRUE}
reload_data <- TRUE
breakseq <- seq(0, 50, 10)

species <- "quercus_robur"
baseline <- 1970:2000 # define temporal baseline (= reference)
calibrations <- (paste0("subset",rep(1:2, each = 5),"_rep", 1:5))
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")

scenario <- "ssp245"

# load simulations
if(reload_data){
  source(file.path(wd, "figures", "scripts", "load_invcal_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd,"figures","data","maps", species, "fitted", paste0("fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd,"figures","data","maps", species, "fitted", paste0("agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd,"figures","data","maps", species, "fitted", paste0("distribution_", scenario, ".rds")))
}

# process maps
source(file.path(wd, "figures", "scripts", "fitness_maps_wagreement.R"))


```

```{r global_distribution_ssp245_qrob, fig.height = 130, fig.cap = "Fitness change relative to 1970-2000 + range shifts (SSP245)", dev = "cairo_pdf", eval = TRUE}

# process maps
source(file.path(wd, "figures", "scripts", "distribution_maps.R"))
plot_grid(fitness_maps, distribution_maps,nrow = 2, rel_heights = c(1,1))

```

```{r global_fitness_ssp585_qrob, fig.height = 75, fig.cap = "Fitness change, relative to 1970-2000.", dev = "cairo_pdf", eval = TRUE}
reload_data <- TRUE
breakseq <- seq(0, 50, 10)

species <- "quercus_robur"
baseline <- 1970:2000 # define temporal baseline (= reference)
calibrations <- (paste0("subset",rep(1:2, each = 5),"_rep", 1:5))
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")

scenario <- "ssp585"

# load simulations
if(reload_data){
  source(file.path(wd, "figures", "scripts", "load_invcal_maps.R"))
}else{
  sim_fitness <- readRDS(file = file.path(wd,"figures","data","maps", species, "fitted", paste0("fitness_", scenario, ".rds")))
  sim_agreement <- readRDS(file = file.path(wd,"figures","data","maps", species, "fitted", paste0("agreement_", scenario, ".rds")))
  sim_distribution <- readRDS(file = file.path(wd,"figures","data","maps", species, "fitted", paste0("distribution_", scenario, ".rds")))
}

# process maps
source(file.path(wd, "figures", "scripts", "fitness_maps_wagreement.R"))


```

```{r global_distribution_ssp585_qrob, fig.height = 130, fig.cap = "Fitness change relative to 1970-2000 + range shifts (SSP585)", dev = "cairo_pdf", eval = TRUE}

# process maps
source(file.path(wd, "figures", "scripts", "distribution_maps.R"))
plot_grid(fitness_maps, distribution_maps,nrow = 2, rel_heights = c(1,1))

```

```{r global_fitness_ssp585_qrob_csdm, fig.height = 75, fig.cap = "CSDM. Fitness change, relative to 1970-2000.", dev = "cairo_pdf"}

breakseq <- seq(0, 20, 5)

species <- "quercus_robur"
models <- c("lasso_glm", "random_forest", "gam", "brt")
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")

scenario <- "ssp585"

# load simulations
source(file.path(wd, "figures", "scripts", "load_csdm_maps.R"))

crs(sim_fitness) <- "EPSG:4326"
crs(sim_distribution) <- "EPSG:4326"
crs(sim_agreement) <- "EPSG:4326"

# process maps
source(file.path(wd, "figures", "scripts", "fitness_maps_wagreement.R"))

```

```{r global_distribution_ssp585_qrob_csdm, fig.height = 130, fig.cap = "CSDM. Fitness change relative to 1970-2000 + range shifts (SSP585)", dev = "cairo_pdf"}

# process maps
source(file.path(wd, "figures", "scripts", "distribution_maps.R"))
plot_grid(fitness_maps, distribution_maps,nrow = 2, rel_heights = c(1,1))

```




\newpage

## France

```{r raw, fig.height = 60, fig.cap = "ANOVA on raw outputs (21-year average fitness)", eval = TRUE}

species <- "fagus_sylvatica"

baseline <- 1970:2000 # define temporal baseline (= reference)

calibrations <- c("expert", paste0("subset",rep(1:10, each = 10),"_rep", 1:10))
scenarios <- c("ssp245", "ssp585")
gcms <- c("GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL")

country <- "France"

# load simulations of PBMs
ncores <- 10
source(file.path(wd, "figures", "scripts", "load_yearly_fitness.R"))
sim_copy <- simulations_pbm

# load simulations of CSDMs
source(file.path(wd, "figures", "scripts", "load_yearly_fitness_csdm.R"))

# 21-year average fitness
simulations_pbm <- simulations_pbm %>%
  group_by(cal, gcm, ssp) %>% 
  mutate(y = rollapply(y,21,mean,align='center',fill=NA)) %>%
  ungroup %>% na.omit()

# # run ANOVA on raw outputs, make figures
# source(file.path(wd, "figures", "scripts", "anova_raw_outputs.R"))
# 
# plot_grid(
#   plot_grid(trend_unc, unc_decomp  + theme(legend.position = 'none'), rel_widths = c(0.6, 0.37)),
#   get_legend(unc_decomp), 
#   ncol = 1, 
#   rel_heights = c(1,0.1))

```

```{r cubic_spline, fig.height = 60, fig.cap = "ANOVA on forced outputs (21-year average fitness - cubic spline, automatic)", eval = FALSE}

df <- NULL # equivalent number of degrees of freedom, if NULL => automatic
source(file.path(wd, "figures", "scripts", "cubic_splines.R"))

# run ANOVA on forced outputs, make figures
source(file.path(wd, "figures", "scripts", "anova_forced_outputs.R"))

plot_grid(
  plot_grid(trend_unc, unc_decomp  + theme(legend.position = 'none'), rel_widths = c(0.6, 0.37)),
  get_legend(unc_decomp), 
  ncol = 1, 
  rel_heights = c(1,0.1))

```

```{r cubic_spline2, fig.height = 60, fig.cap = "ANOVA on forced outputs (21-year average fitness - cubic spline, DF=4)", eval = FALSE}

df <- 4 # equivalent number of degrees of freedom, if NULL => automatic
source(file.path(wd, "figures", "scripts", "cubic_splines.R"))

# run ANOVA on forced outputs, make figures
source(file.path(wd, "figures", "scripts", "anova_forced_outputs.R"))

plot_grid(
  plot_grid(trend_unc, unc_decomp  + theme(legend.position = 'none'), rel_widths = c(0.6, 0.37)),
  get_legend(unc_decomp), 
  ncol = 1, 
  rel_heights = c(1,0.1))

```

```{r cubic_spline3, fig.height = 60, fig.cap = "ANOVA on forced outputs (21-year average fitness - cubic spline, DF=6)", eval = FALSE}

df <- 6 # equivalent number of degrees of freedom, if NULL => automatic
source(file.path(wd, "figures", "scripts", "cubic_splines.R"))

# run ANOVA on forced outputs, make figures
source(file.path(wd, "figures", "scripts", "anova_forced_outputs.R"))

plot_grid(
  plot_grid(trend_unc, unc_decomp  + theme(legend.position = 'none'), rel_widths = c(0.6, 0.37)),
  get_legend(unc_decomp), 
  ncol = 1, 
  rel_heights = c(1,0.1))

```

```{r 4thorder_poly, fig.height = 60, fig.cap = "ANOVA on forced outputs (21-year average fitness - 4th order polynomial)", eval = FALSE}

ndeg_poly <- 4 # order of polynomial fit
source(file.path(wd, "figures", "scripts", "polynomial_fits.R"))

# run ANOVA on forced outputs, make figures
source(file.path(wd, "figures", "scripts", "anova_forced_outputs.R"))

plot_grid(
  plot_grid(trend_unc, unc_decomp  + theme(legend.position = 'none'), rel_widths = c(0.6, 0.37)),
  get_legend(unc_decomp), 
  ncol = 1, 
  rel_heights = c(1,0.1))

```

```{r raw_11yr, fig.height = 60, fig.cap = "ANOVA on raw outputs (11-year average fitness)", eval = FALSE}

# 11-year average fitness
simulations <- sim_copy %>%
  group_by(cal, gcm, ssp) %>% 
  mutate(y = rollapply(y,11,mean,align='center',fill=NA)) %>%
  ungroup %>% na.omit()

# run ANOVA on raw outputs, make figures
source(file.path(wd, "figures", "scripts", "anova_raw_outputs.R"))

plot_grid(
  plot_grid(trend_unc, unc_decomp  + theme(legend.position = 'none'), rel_widths = c(0.6, 0.37)),
  get_legend(unc_decomp), 
  ncol = 1, 
  rel_heights = c(1,0.1))

```

```{r uncertainty_cascade, fig.height = 130, fig.width = 70, fig.cap = "Uncertainty cascade", eval = TRUE}

# make figure
source(file.path(wd, "figures", "scripts", "uncertainty_cascade_permethod.R"))

unc_cascade

```

\newpage

## Germany

```{r raw_ger, fig.height = 60, fig.cap = "ANOVA on raw outputs (21-year average fitness)", eval = FALSE}

country <- "Germany"

# load simulations
source(file.path(wd, "figures", "scripts", "load_yearly_fitness.R"))
sim_copy <- simulations

# 21-year average fitness
simulations <- simulations %>%
  group_by(cal, gcm, ssp) %>% 
  mutate(y = rollapply(y,21,mean,align='center',fill=NA)) %>%
  ungroup %>% na.omit()

# run ANOVA on raw outputs, make figures
source(file.path(wd, "figures", "scripts", "anova_raw_outputs.R"))

plot_grid(
  plot_grid(trend_unc, unc_decomp  + theme(legend.position = 'none'), rel_widths = c(0.6, 0.37)),
  get_legend(unc_decomp), 
  ncol = 1, 
  rel_heights = c(1,0.1))

```

```{r cubic_spline3_ger, fig.height = 60, fig.cap = "ANOVA on forced outputs (21-year average fitness - cubic spline, DF=6)", eval = FALSE}

df <- 6 # equivalent number of degrees of freedom, if NULL => automatic
source(file.path(wd, "figures", "scripts", "cubic_splines.R"))

# run ANOVA on forced outputs, make figures
source(file.path(wd, "figures", "scripts", "anova_forced_outputs.R"))

plot_grid(
  plot_grid(trend_unc, unc_decomp  + theme(legend.position = 'none'), rel_widths = c(0.6, 0.37)),
  get_legend(unc_decomp), 
  ncol = 1, 
  rel_heights = c(1,0.1))

```

\newpage

## Poland

```{r raw_pol, fig.height = 60, fig.cap = "ANOVA on raw outputs (21-year average fitness)", eval = FALSE}

country <- "Poland"

# load simulations
source(file.path(wd, "figures", "scripts", "load_yearly_fitness.R"))
sim_copy <- simulations

# 21-year average fitness
simulations <- simulations %>%
  group_by(cal, gcm, ssp) %>% 
  mutate(y = rollapply(y,21,mean,align='center',fill=NA)) %>%
  ungroup %>% na.omit()

# run ANOVA on raw outputs, make figures
source(file.path(wd, "figures", "scripts", "anova_raw_outputs.R"))

plot_grid(
  plot_grid(trend_unc, unc_decomp  + theme(legend.position = 'none'), rel_widths = c(0.6, 0.37)),
  get_legend(unc_decomp), 
  ncol = 1, 
  rel_heights = c(1,0.1))

```

```{r cubic_spline3_pol, fig.height = 60, fig.cap = "ANOVA on forced outputs (21-year average fitness - cubic spline, DF=6)", eval = FALSE}

df <- 6 # equivalent number of degrees of freedom, if NULL => automatic
source(file.path(wd, "figures", "scripts", "cubic_splines.R"))

# run ANOVA on forced outputs, make figures
source(file.path(wd, "figures", "scripts", "anova_forced_outputs.R"))

plot_grid(
  plot_grid(trend_unc, unc_decomp  + theme(legend.position = 'none'), rel_widths = c(0.6, 0.37)),
  get_legend(unc_decomp), 
  ncol = 1, 
  rel_heights = c(1,0.1))

```

\newpage

## United Kingdom

```{r raw_uk, fig.height = 60, fig.cap = "ANOVA on raw outputs (21-year average fitness)", eval = FALSE}

country <- "United Kingdom"

# load simulations
source(file.path(wd, "figures", "scripts", "load_yearly_fitness.R"))
sim_copy <- simulations

# 21-year average fitness
simulations <- simulations %>%
  group_by(cal, gcm, ssp) %>% 
  mutate(y = rollapply(y,21,mean,align='center',fill=NA)) %>%
  ungroup %>% na.omit()

# run ANOVA on raw outputs, make figures
source(file.path(wd, "figures", "scripts", "anova_raw_outputs.R"))

# plot_grid(
#   plot_grid(trend_unc, unc_decomp  + theme(legend.position = 'none'), rel_widths = c(0.6, 0.37)),
#   get_legend(unc_decomp), 
#   ncol = 1, 
#   rel_heights = c(1,0.1))

```

```{r cubic_spline3_uk, fig.height = 60, fig.cap = "ANOVA on forced outputs (21-year average fitness - cubic spline, DF=6)", eval = FALSE}

df <- 6 # equivalent number of degrees of freedom, if NULL => automatic
source(file.path(wd, "figures", "scripts", "cubic_splines.R"))

# run ANOVA on forced outputs, make figures
source(file.path(wd, "figures", "scripts", "anova_forced_outputs.R"))

plot_grid(
  plot_grid(trend_unc, unc_decomp  + theme(legend.position = 'none'), rel_widths = c(0.6, 0.37)),
  get_legend(unc_decomp), 
  ncol = 1, 
  rel_heights = c(1,0.1))

```

```{r uncertainty_cascade_uk, fig.height = 130, fig.width = 70, fig.cap = "Uncertainty cascade", eval = FALSE}

# make figure
source(file.path(wd, "figures", "scripts", "uncertainty_cascade.R"))

unc_cascade

```